Set a default value of 1 for remote download concurrency
ansible/ansible-hub-ui pull request #1034
Opened 2021-10-04 18:53 UTC by jctanner

Thank you for a new Pull Request!

Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ansible/ansible-hub-ui/blob/master/developer_guidelines.md

Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.

Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description as necessary to get the reviewer up to the same domain knowledge level as yourself
* Keep code changes as short as possible and implementing a single feature/fix/refactoring, when possible

Links [Optional]
----------------

* http://documentation.for/library/that/I/am/adding
* [PR relevant issue or pull_request](#123)

Steps for Testing/QA [Optional]
-------------------------------

If there are any manual steps that you would like the reviewer(s) to take to verify your changes, please describe in detail the steps to reproduce the features added by the pull request, or the bug before and after the change.

2021-10-04 21:26 UTC, himdel commented on src/components/repositories/remote-form.tsx
> +      this.props.remote.download_concurrency = 10;
This has to depend on `remoteType` - if the type is `registry`, the field is not required (and null seems to be a valid value on the backend).

2021-10-04 21:27 UTC, himdel commented on src/components/repositories/remote-form.tsx
> +      this.props.remote.download_concurrency = 10;
(Otherwise LGTM, except the value (`10`) doesn't match the PR description (`1`).)

2021-10-05 12:15 UTC, jctanner commented on src/components/repositories/remote-form.tsx
> +      this.props.remote.download_concurrency = 10;
Got it, thank you @himdel

2021-10-05 14:39 UTC, himdel approved these changes

2021-10-05 14:41 UTC, himdel requested changes
approved too soon, sorry .. we can't change props from inside the component

2021-10-05 14:44 UTC, himdel commented on src/components/repositories/remote-form.tsx
> +      this.props.remote.download_concurrency = 10;
```suggestion
      this.updateRemote(10, 'download_concurrency');
```

2021-10-05 14:44 UTC, jctanner commented on src/components/repositories/remote-form.tsx
> +      this.props.remote.download_concurrency = 10;
Ah, I'll try that.

2021-10-05 15:59 UTC, himdel approved these changes
Works for me :+1: :)

2021-10-05 21:36 UTC, merged