create single  'Get Token' button for all local repos
ansible/ansible-hub-ui pull request #1257
Opened 2021-11-18 21:10 UTC by ShaiahWren

Issue: https://issues.redhat.com/browse/AAH-903

Assignment:

1. Only one "Get Token" button for the list view in the header. Only when 'local' repos tab is selected
2. Button does not redirect to a new tab

Before: 
![Screen Shot 2021-11-18 at 4 08 48 PM](https://user-images.githubusercontent.com/64337863/142497181-890e11fa-b1d2-4062-9831-d62e8a87787c.png)

After:  
![Screen Shot 2021-11-18 at 4 09 15 PM](https://user-images.githubusercontent.com/64337863/142497208-640aa4d1-fdc7-47e9-bdf2-af4d6fb24498.png)

2021-11-23 21:27 UTC, himdel approved these changes

2021-11-29 12:43 UTC, ZitaNemeckova requested changes

2021-11-29 12:43 UTC, ZitaNemeckova commented on src/containers/repositories/repository-list.tsx
> +              {params.tab == 'local' && (
@ShaiahWren This should be in `BaseHeader` param `pageControls`. See https://github.com/ansible/ansible-hub-ui/blob/2e1946f7c7e344c7bc4d6a017e0199ba6aeb6870/src/containers/group-management/group-detail.tsx#L200-L215 for reference.

After moving it there shouldn't be any need for new CSS and it should consistent with similar pages.

2021-12-01 22:19 UTC, awcrosby commented
(adding this to a few recently updated PRs…) We need CI in this repo that enforces this, but for now please:
* Add a line to at least one of your commits that says `Issue: AAH-####` (in the future it is best to be the first commit as it gets included in the initial PR description by default)
* Ensure when merging that the `Issue: AAH-####` is part of commit message via the “Squash ‘n’ Merge” description

2021-12-02 20:45 UTC, ShaiahWren commented
Issue: AAH-903

2021-12-02 20:46 UTC, merged

2021-12-13 20:47 UTC, himdel commented
(backport failed because of a conflict with (missing) #1259 , backporting that one first)