Adding Secure URL validation
ansible/ansible-hub-ui pull request #1490
Opened 2022-01-10 13:17 UTC by brumik

Issue: https://issues.redhat.com/browse/AAH-1195

**Before**
![Screenshot from 2022-01-10 14-14-26](https://user-images.githubusercontent.com/8531681/148772240-fac02d90-b192-4bd6-bed2-cb65625eef7c.png)
![Screenshot from 2022-01-10 14-14-15](https://user-images.githubusercontent.com/8531681/148772246-632260ab-cec1-4b2a-9b6a-9d86da3cb894.png)

**After**
![Screenshot from 2022-01-10 14-12-38](https://user-images.githubusercontent.com/8531681/148772266-d917e2da-2dc9-4790-95c1-e9915b67304f.png)
![Screenshot from 2022-01-10 14-12-29](https://user-images.githubusercontent.com/8531681/148772268-ada84265-6cba-49d5-b00d-7b09447fe2bd.png)
![Screenshot from 2022-01-10 14-12-20](https://user-images.githubusercontent.com/8531681/148772270-0246525f-9e41-4787-ab07-cee9c1a0082d.png)

2022-01-10 14:12 UTC, ironfroggy commented
This issue was discussed with some open questions that need to be resolved. Please do not merge this PR until then!

2022-01-10 14:13 UTC, ironfroggy requested changes
I'm leaving this non-approve review to mark the PR as having outstanding questions that need to be resolved on the Jira ticket before proceeding.

2022-01-10 14:16 UTC, MilanPospisil commented
One test file is failing. Look at the details of Cypress (at this page), click details and scroll through the log which file it is. You need to update the test to match new functionality. Go to the folder test in terminal and run command: npm run cypress. This will open window with all the tests, select the one that fails and it will launch the browser, where you can see the run of the test (code and what is going on in the app in the browser). Inside the test/cypress/integration, you can find our test files. You will need some knowledge of cypress, but its not really hard - its some asynchronous javascript, that manipulates application using cypress API, css selectors and such. I suggests that you focus mostly on typing data in the url line, because you added initial URL state and the tests dont know about it and blindly expects that its empty.

2022-01-10 15:06 UTC, brumik commented
@MilanPospisil Thank you for the long description, I am well familiar with Cypress and it's setup/run/ci. 

As @ironfroggy wrote there is a discussion in Jira so I will not touch this PR until that's resolved.

2022-01-20 13:38 UTC, brumik commented
Closing in favour of a forked branch #1529

2022-01-20 13:38 UTC, closed without merging