[Signing 2] Add signed filter to the toolbar
ansible/ansible-hub-ui pull request #1626
Opened 2022-02-09 08:55 UTC by brumik

![Screenshot from 2022-02-09 09-52-26](https://user-images.githubusercontent.com/8531681/153160233-66467f6b-ec1a-460e-be42-80e2fd8783ef.png)

2022-03-02 09:44 UTC, ZitaNemeckova requested changes
So I have clean DB and latest backend master. I uploaded arista cvp v.3.1.0 collection. It's auto approved. And when I try to filter by `Sign state` a get 400 error in console.

```
Request URL: http://localhost:8002/api/automation-hub/_ui/v1/repo/published/?sign_state=unsigned&deprecated=false&offset=0&limit=10

{"errors":[{"status":"400","code":null,"title":"Invalid input.","detail":"Invalid Filter: 'sign_state'","source":{"parameter":"errors"}}]}

```
<img width="1388" alt="Screenshot 2022-03-02 at 10 42 36" src="https://user-images.githubusercontent.com/9210860/156336291-b76eaf74-bd6e-4cb1-94e9-ffc799918bba.png">

2022-03-02 11:33 UTC, brumik commented
@ZitaNemeckova  Well, not having the backend to filter by something is problematic. I would lie if I would say I still remember the details but I think these PRs supposed to work **only** with this backend branch https://github.com/ansible/galaxy_ng/pull/1145 which adds actually signing to it.

Though let me know if we need to make this whole feature to not cause problems on backends which are not supporting signing (but as a feature we are not backporting this so I don't know if there is a need for it)

2022-03-03 09:44 UTC, ZitaNemeckova commented
To make sure I do understand it correctly. Not having a sign feature flag means an user can see all signing related info like labels (because they can sync it from repo that has signed collections) but cannot sign it's own collections. So seeing a collection the user uploaded and approved as signed in this filter is correct, right?

@himdel @brumik Code-wise it looks good, it works well with the backend PR. I'm just not sure what should and shouldn't be hidden when sign feature flag is false.

2022-03-04 02:13 UTC, himdel commented
I think as long as things don't blow up, hiding Unsigned is not critical.. there were some discussions about what to do when signing is not enabled, but syncing from a repository where signing is enabled, and there is a case for still showing that information in such case.

However we may be able to tell these cases apart and hide it when `sign_state` / `signatures` is not present.

2022-03-08 22:54 UTC, himdel commented on src/components/collection-list/collection-filter.tsx
> +          { id: 'partial', title: 'Partial' },
```suggestion
        title: t`Sign state`,
        inputType: 'select' as const,
        options: [
          { id: 'signed', title: t`Signed` },
          { id: 'unsigned', title: t`Unsigned` },
          { id: 'partial', title: t`Partial` },
```

2022-03-08 22:55 UTC, himdel commented on src/components/collection-list/collection-filter.tsx
> +                    keywords: 'keywords',
```suggestion
                    sign_state: t`Sign state`,
                    tags: t`Tags`,
                    keywords: t`Keywords`,
```

2022-03-08 22:56 UTC, himdel commented on src/components/collection-list/collection-filter.tsx
> +        title: 'Sign state',
```suggestion
        title: t`Sign state`,
```

2022-03-22 00:56 UTC, himdel approved these changes

2022-03-22 08:10 UTC, merged