Rework groups view
ansible/ansible-hub-ui pull request #1797
Opened 2022-03-21 11:33 UTC by jerabekjiri

Issue: [AAH-1130](https://issues.redhat.com/browse/AAH-1130)

This PR adds group roles management and the process of adding roles to the group.

Using `RoleListTable` component from [#1762](https://github.com/ansible/ansible-hub-ui/pull/1762).

### Access tab with list of roles
![Screenshot from 2022-03-21 12-26-26](https://user-images.githubusercontent.com/19647757/159252728-39491847-d68d-480b-a242-35874561154e.png)

### Delete role modal
![Screenshot from 2022-03-20 01-35-46](https://user-images.githubusercontent.com/19647757/159253037-aad73ca4-bcda-4ff3-bee4-8d54ac247fb6.png)

### Empty list of roles
![Screenshot from 2022-03-19 22-49-53](https://user-images.githubusercontent.com/19647757/159253440-d9447029-bfa2-4829-8de8-14c31a9c0d9f.png)

### Wizard - Select role(s) step
![Screenshot from 2022-03-21 12-26-59](https://user-images.githubusercontent.com/19647757/159252818-b491d4b2-d087-4519-8130-83f1a7574372.png)

### Wizard - Preview roles
![Screenshot from 2022-03-21 12-27-08](https://user-images.githubusercontent.com/19647757/159252938-7873f41b-9e91-46dc-8338-42d1c261670d.png)

2022-04-06 02:21 UTC, jerabekjiri commented
I think PR is ready for review.

Adding additional screen changes:

- disabling roles that are already assigned to the group (for now)
  ![Screenshot from 2022-04-06 01-53-37](https://user-images.githubusercontent.com/19647757/161882306-a0e27739-5e47-4dea-a6b3-2b004b13eaa3.png)

  ![Screenshot from 2022-04-06 04-06-06](https://user-images.githubusercontent.com/19647757/161882207-235a55f3-1462-485e-8006-82b00186c16f.png)

- updated preview roles with bold category permissions 
  ![Screenshot from 2022-04-06 04-06-22](https://user-images.githubusercontent.com/19647757/161882171-1b2fb28e-aac9-4a60-bb5d-aeef6388b851.png)

- Wizard empty state (group has no assignable roles)
![Screenshot from 2022-04-06 01-09-48](https://user-images.githubusercontent.com/19647757/161882426-c3c8aad0-0b31-44e9-83db-c3914980074c.png)

2022-04-06 20:21 UTC, jerabekjiri commented
Reworked the `group_management` test, but for the other tests we would need to create a custom role with permissions and that's not possible yet. `galaxykit` doesn't support that as well. So I think skipping the tests and adding them later when the feature for creating roles is merged?

2022-04-07 02:00 UTC, himdel commented
Agreed, `it.skip` should work for now.

(Once we can create roles via the UI, we should unskip the tests even if we have to do the setup via UI code (as we'll want to have tests for that anyway) - but that's probably for a second PR, as role creation UI is not merged yet either)

2022-04-07 12:45 UTC, himdel commented on src/api/generic-pulp.ts
> +  apiPath = 'roles/';
this will break task detail screen

if you need to list roles, create a new api file?

2022-04-07 13:15 UTC, himdel commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.scss
> +.empty-state-box {
any new css class being introduced should start with `hub-` (https://github.com/ansible/ansible-hub-ui/pull/1657)

2022-04-07 13:23 UTC, himdel commented on src/api/group-role.ts
> +  }
this is a surprising combination of async and promise, and is waiting in places it probably shouldn't

```suggestion
  getRolesWithPermissions(id, params?) {
    const assignedRoles = this.list(
      params,
      this.apiPath + `${id}/roles/`,
    );

    const allRoles = RoleAPI.list();

    return Promise.all([assignedRoles, allRoles])
      .then(([assigned, all]) => {
        // match roles with assigned roles
        const data = assigned.data.results
          .map(({ role, pulp_href }) => {
            const data = all['data'].results.find(
              ({ name }) => name === role,
            );
            if (data) {
              return {
                ...data,
                // swap pulp_href role with assigned pulp_href role
                // to delete the assigned role
                pulp_href,
              };
            }
          })
          .filter(Boolean);

        return {
          data,
          count: data.length,
        };
      })
  }
```

2022-04-07 13:26 UTC, himdel commented on src/api/group-role.ts
> +    return this.http.delete(this.apiPath + `${id}/roles/${pulpId}/`);
looks like 3 calls in this file need to override the path ... sounds like you need a second `RoleAPI` with the right apiPath so that you don't have to do this

2022-04-07 13:34 UTC, himdel commented on test/cypress.env.json.template
> +  "pulpPrefix":"/pulp/api/v3/",
:+1: related to #1857

2022-04-07 18:29 UTC, newswangerd requested changes

2022-04-07 18:29 UTC, newswangerd commented on src/api/group-role.ts
> +import { RoleAPI } from './role';
Duplicate imports with the same name.

2022-04-07 18:29 UTC, newswangerd commented on src/api/group-role.ts
> +import { RoleAPI } from './role';
There really should just be one RoleAPI. Defining the same thing in two different files is confusing.

2022-04-07 18:29 UTC, newswangerd commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.tsx
> +        You are about to remove <strong>{selectedDeleteRole?.name}</strong>{' '}
"You are about to remove {role} from {group}".

2022-04-07 18:29 UTC, newswangerd commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.tsx
> +        This will also remove all associated permissions under this role.
"This will revoke all permissions associated with this role from the group."

2022-04-08 11:55 UTC, jerabekjiri commented on src/api/group-role.ts
> +import { RoleAPI } from './role';
> There really should just be one RoleAPI. Defining the same thing in two different files is confusing.

API path for just roles is `/pulp/api/v3/roles`, but the path for managing assigned roles to the group is `pulp/api/v3/groups/roles`. My solution works the same based on how our API interfaces are built and composed on UI, but I can merge the group-role.ts and role.ts files, but that will mean setting a different `apiPath` for every method.

2022-04-08 11:57 UTC, jerabekjiri commented on src/api/pulp.ts
> +  list(params?, apiPath?) {
yes, that's what I was planning on initially. Updated and removed from `RoleAPI`, `GenericPulpAPI` and `TaskManagementAPI`.

2022-04-08 12:11 UTC, jerabekjiri commented on src/api/group-role.ts
> +    return this.http.delete(this.apiPath + `${id}/roles/${pulpId}/`);
So maybe this would be possible solution by extending the pulp path like this? I know this introduces a new way of setting path because we already have `apiPath` for this?
```
export class PulpAPI extends BaseAPI {
  constructor(extendPath?: string) {
    if (extendPath) {
      super('/pulp/api/v3/' + extendPath);
    } else {
      super('/pulp/api/v3/');
    }
  }
```
Or do we really want another file just for setting path? Or we could set the `apiPath` in this file (`group-role.ts`) and in container files set the additional path and compose role params there? but that's no good as well.

2022-04-11 12:30 UTC, newswangerd approved these changes

2022-04-11 14:44 UTC, himdel commented on src/containers/group-management/group-detail-role-management/preview-roles.tsx
> +        The following roles will be applied to group:{' '}
Trans

2022-04-11 14:44 UTC, himdel commented on src/containers/group-management/group-detail-role-management/preview-roles.tsx
> +    <div>No roles selected</div>
i18n

2022-04-11 15:46 UTC, jerabekjiri commented on src/containers/group-management/group-detail-role-management/preview-roles.tsx
> +    <div>No roles selected</div>
I missed this, I will remove the part with `selectedRoles` validation. Shouldn't be here anyway, keep the component simple. The validation for empty state can be done elsewhere.

And in the wizard, we can't visit this screen if `selectedRoles` are empty.

2022-04-17 16:32 UTC, himdel commented on src/containers/group-management/group-detail-role-management/preview-roles.tsx
> +  const [category, permission] = perm.split('.');
```suggestion
  const [category, permission] = perm.split('.', 2);
```

(if the string is `foo.a.b.c`, you want permission to be `a.b.c`, not just `a`, right?)

2022-04-17 16:32 UTC, himdel commented on src/components/patternfly-wrappers/wizard-modal.tsx
> +      mainAriaLabel={`${title} content`}
```suggestion
      navAriaLabel={t`${title} steps`}
      mainAriaLabel={t`${title} content`}
```

2022-04-17 16:38 UTC, himdel commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.tsx
> +                          title: t`name`,
```suggestion
                          title: t`Name`,
```

2022-04-17 16:45 UTC, himdel commented on src/containers/group-management/group-detail-role-management/select-roles.tsx
> +                    <strong>Selected Roles</strong>
```suggestion
                    <strong><Trans>Selected Roles</Trans></strong>
```

2022-04-17 16:55 UTC, himdel commented
I didn't really find anything non-i18n related,
stable-4.5 is split already,
so feel free to merge once the above suggestions are resolved :)

2022-04-17 17:12 UTC, himdel commented on src/api/group-role.ts
> +    super('groups/');
... just realized .. how is this differetnt from `apiPath = 'groups/`;`. Isn't it doing exactly the same thing now, with extra code?

2022-04-17 17:18 UTC, himdel commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.tsx
> +            });
this should be identical to...

```suggestion
            const selectedRolesPromises = selectedRoles.map(
              (role) =>
                GroupRoleAPI.addRoleToGroup(group.id, role)
                  .then(() => {
                    addAlert(
                      t`Role ${role.name} has been successfully added to ${group.name}.`,
                      'success',
                    );
                  })
                  .catch((e) => {
                    const { status, statusText, data } = e.response;

                    const errMessage =
                      data?.non_field_errors?.length > 0
                        ? data.non_field_errors[0]
                        : errorMessage(status, statusText);

                    addAlert(
                      t`Role ${role.name} could not be assigned to group ${group.name}.`,
                      'danger',
                      errMessage,
                    );
                  })
                  .finally(() => role);
            );

            Promise.all(selectedRolesPromises).then(() => {
              queryRolesWithPermissions();
              setShowAddRolesModal(false);
              setSelectedRoles([]);
            });
```

(but either works)

2022-04-21 14:24 UTC, jerabekjiri commented on src/containers/group-management/group-detail-role-management/group-detail-role-management.tsx
> +            });
thanks, makes sense, with `finally`, no need for `allSettled`

2022-04-21 14:39 UTC, jerabekjiri commented on src/api/group-role.ts
> +    super('groups/');
Well, this goes back to our previous conversation https://github.com/ansible/ansible-hub-ui/pull/1797#discussion_r845133535 , where `apiPath` had to be overwritten and then passed in every method call. With `super` it gets set automatically.

2022-04-25 02:55 UTC, himdel commented on src/api/group-role.ts
> +    super('groups/');
This works, we can unify that separately :+1:

2022-04-25 03:22 UTC, himdel commented
The select roles screen does double scrollbars now...

![20220425031738](https://user-images.githubusercontent.com/289743/165015445-21d4cf8b-5cb9-45a6-9e72-d2a7fc54d633.png)

Looks like this fixes it... (+ a few more cleanups)

```diff
diff --git a/src/components/patternfly-wrappers/pagination.tsx b/src/components/patternfly-wrappers/pagination.tsx
index c1814a65..a6df7bf5 100644
--- a/src/components/patternfly-wrappers/pagination.tsx
+++ b/src/components/patternfly-wrappers/pagination.tsx
@@ -31,8 +31,6 @@ interface IProps {
 
   /** Options for the number of items that can be displayed per page */
   perPageOptions?: number[];
-
-  style?: object;
 }
 
 export class Pagination extends React.Component<IProps> {
@@ -44,7 +42,6 @@ export class Pagination extends React.Component<IProps> {
       isTop,
       perPageOptions,
       isCompact,
-      style,
     } = this.props;
 
     const extraProps = {};
@@ -75,7 +72,6 @@ export class Pagination extends React.Component<IProps> {
           items: null,
         }}
         toggleTemplate={(props) => <ToggleTemplate ofWord={t`of`} {...props} />}
-        style={style}
       />
     );
   }
diff --git a/src/containers/group-management/group-detail-role-management/group-detail-role-management.scss b/src/containers/group-management/group-detail-role-management/group-detail-role-management.scss
index d5602f2a..e19ddd69 100644
--- a/src/containers/group-management/group-detail-role-management/group-detail-role-management.scss
+++ b/src/containers/group-management/group-detail-role-management/group-detail-role-management.scss
@@ -9,10 +9,13 @@
   padding: 1rem 1.5rem 0;
 
   .hub-select-roles-content {
-    height: 530px;
     overflow: auto;
   }
 
+  .pf-c-pagination.pf-m-bottom {
+    padding-top: 0;
+  }
+
   .hub-permission {
     margin: 3px;
   }
diff --git a/src/containers/group-management/group-detail-role-management/select-roles.tsx b/src/containers/group-management/group-detail-role-management/select-roles.tsx
index 91226d4d..b69b9dd5 100644
--- a/src/containers/group-management/group-detail-role-management/select-roles.tsx
+++ b/src/containers/group-management/group-detail-role-management/select-roles.tsx
@@ -231,7 +231,6 @@ const SelectRoles: React.FC<SelectRolesProps> = ({
               params={localParams}
               updateParams={(p) => setLocalParams(p)}
               count={rolesItemCount}
-              style={{ padding: '0px' }}
             />
           </FlexItem>
         )}
@@ -239,4 +238,5 @@ const SelectRoles: React.FC<SelectRolesProps> = ({
     </div>
   );
 };
+
 export default SelectRoles;
diff --git a/src/containers/group-management/group-list.tsx b/src/containers/group-management/group-list.tsx
index f4651c96..38b51e31 100644
--- a/src/containers/group-management/group-list.tsx
+++ b/src/containers/group-management/group-list.tsx
@@ -407,13 +407,9 @@ class GroupList extends React.Component<RouteComponentProps, IState> {
           onClick={() => {
             this.setState({
               selectedGroup: { ...group },
-              redirect: formatPath(
-                Paths.groupDetail,
-                {
-                  group: group.id,
-                },
-                { isEditing: true },
-              ),
+              redirect: formatPath(Paths.groupDetail, {
+                group: group.id,
+              }),
             });
           }}
         >
```

![20220425031806](https://user-images.githubusercontent.com/289743/165015497-a85eca90-2df4-4112-a46f-ae60a9d39b9c.png)
![20220425032059](https://user-images.githubusercontent.com/289743/165015498-7144f4de-ad77-4d96-8ee6-76d1db270e66.png)

2022-04-25 03:38 UTC, himdel commented
The list view in Access tab - expanded roles always show no permissions, despite the data...

Unknown permissions should still be visible when showing what the group can do,
while the "No permission" lines should be hidden in non-edit view.

![20220425032535](https://user-images.githubusercontent.com/289743/165015890-d498bb39-15e9-44e2-a41e-41b02cf7a8a6.png)

looks like this now only works for our permissions, not core, etc.

2022-04-25 06:53 UTC, himdel commented
Restarting tests after https://github.com/ansible/ansible-hub-ui/pull/1974

2022-04-26 14:21 UTC, jerabekjiri commented
@himdel What about this? Hide `No permission` and added `Custom permissions` (or maybe call it `Other permissions`?) to display custom permissions? 
![Screenshot from 2022-04-26 16-18-25](https://user-images.githubusercontent.com/19647757/165321330-d90342f2-e9bd-483b-ba59-9d6a2a340afc.png)

2022-04-26 16:48 UTC, himdel approved these changes
Looks ready as well :+1:

(just a rebase.. :))

2022-04-26 20:40 UTC, merged