[WIP] Add Group management page
ansible/ansible-hub-ui pull request #184
Opened 2020-08-25 14:02 UTC by ZitaNemeckova

Related to https://github.com/ansible/galaxy_ng/issues/191

TODO:
- [ ] View table
- [ ] Create page
- [ ] Edit page
- [ ] Permission table
- [ ] Edit permission table
- [ ] RBAC check

Table:
<img width="1670" alt="Screenshot 2020-08-25 at 15 55 23" src="https://user-images.githubusercontent.com/9210860/91183581-ef04e580-e6eb-11ea-8809-31fb9636a0bd.png">

Use https://github.com/ansible/ansible-hub-ui/pull/183/files#diff-071e403338d465d01a186335785d939a

2020-09-03 23:52 UTC, newswangerd requested changes
I think you can fix the users page not updating with `Promise.all()`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

A few small changes. Looking good so far!

2020-09-03 23:52 UTC, newswangerd commented on src/constants.tsx
> +      id: 1,
What are these IDs for?

2020-09-03 23:52 UTC, newswangerd commented on src/containers/group-management/group-detail.tsx
> +                  isDisabled={!this.state.editPermissions}
If there aren't any permissions selected when the field is disabled, it should say something like "No permissions selected"

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6063371/92183517-abf9ef00-ee1c-11ea-84b3-3c36161a050a.png">

2020-09-03 23:52 UTC, newswangerd commented on src/containers/group-management/group-detail.tsx
> +                  selectedPermissions={selectedPermissions.filter(selected =>
The following permissions don't seem to show up correctly in the UI when they are set on a group:
- all permissions for users
- delete_synclist
- view_synclist

I think this is because the number of results that get returned on the api call is limited to 10

2020-09-03 23:52 UTC, newswangerd commented on src/containers/group-management/group-detail.tsx
> +                GroupAPI.addPermission(this.state.group.id, {
An alert should get added if a permission can't be added to a group.

2020-09-04 11:29 UTC, ZitaNemeckova commented on src/constants.tsx
> +      id: 1,
Unused. Removed.

2020-09-04 11:29 UTC, ZitaNemeckova commented on src/containers/group-management/group-detail.tsx
> +                  isDisabled={!this.state.editPermissions}
Fixed.

2020-09-04 11:29 UTC, ZitaNemeckova commented on src/containers/group-management/group-detail.tsx
> +                  selectedPermissions={selectedPermissions.filter(selected =>
Fixed.

2020-09-04 11:29 UTC, ZitaNemeckova commented on src/containers/group-management/group-detail.tsx
> +                GroupAPI.addPermission(this.state.group.id, {
Added.

2020-09-04 13:21 UTC, newswangerd approved these changes

2020-09-04 13:25 UTC, merged