Add MultiRepo select to navbar
ansible/ansible-hub-ui pull request #187
Opened 2020-09-07 09:13 UTC by ZitaNemeckova

Related to https://github.com/ansible/galaxy_ng/issues/296

TODO: =
- [ ] Add select to navbar
- [ ] Fix select styling
- [ ] Persist selection when reload
- [ ] Add new routes
- [ ] Use API according to selected repo

2020-09-10 01:28 UTC, newswangerd reviewed
I also left you some notes on slack about why the context doesn't seem to update the app.

2020-09-10 01:28 UTC, newswangerd commented on src/api/collection.ts
> +  listByNamespace(namespace: string, params?: {}, repo?: string) {
what is listByNamespace for? Can't we just use list with the `?namespace=` param?

2020-09-10 01:28 UTC, newswangerd commented on src/api/collection.ts
> +      DEPLOYMENT_MODE === Constants.INSIGHTS_DEPLOYMENT_MODE
I noticed you're calling `INSIGHTS_DEPLOYMENT_MODE` a lot to toggle between the `collections/` and `repo/<reponame>/` apis. My suggestion is to exclusively use the new `repo/` api endpoint. We want to get rid of the old `collections` anyway. 

Instead of checking the depolyment mode and toggling between the two endpoints, just set `appContext.selectedRepo = 'automation-hub'` for insights mode and don't add any logic to change it. That way, when the app is in insights mode it will always just look up `repo/automation-hub/` which is what `collections/` does anyway.

2020-09-10 01:28 UTC, newswangerd commented on src/components/collection-list/collection-list-item.tsx
> +      DEPLOYMENT_MODE === Constants.INSIGHTS_DEPLOYMENT_MODE
I'm tempted to say we should just use the new `repo/` paths for all our links in insights mode. As long as the old URLs still work for people to link to stuff in hub, it doesn't matter that all the internal links prefix everything with `repo/`

2020-09-10 01:28 UTC, newswangerd commented on src/constants.tsx
> +  static DEAFAULTREPO = 'Red Hat Certified';
make the default `published` for on prem and `automation-hub` for insights. (We'll probably change insights to use published as soon)

2020-09-10 01:28 UTC, newswangerd commented on src/containers/collection-detail/collection-content.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
These checks to see if there's a repo set and to set a default repo should just go in `standalone-loader` and `insights-loader` so you only need to me this check once for the whole app.

2020-09-10 01:28 UTC, newswangerd commented on src/containers/collection-detail/collection-detail.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
Same here.

2020-09-10 01:28 UTC, newswangerd commented on src/containers/collection-detail/collection-docs.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
same here

2020-09-10 01:28 UTC, newswangerd commented on src/containers/collection-detail/collection-import-log.tsx
> +    const { repo } = this.state;
same here

2020-09-10 01:28 UTC, newswangerd commented on src/containers/search/search.tsx
> +    const { repo } = this.state;
same here

2020-09-10 01:28 UTC, newswangerd commented on src/loaders/standalone/standalone-loader.tsx
> +                    <SelectOption key={'published'} value={'Published'} />
move published to the top

2020-09-10 01:28 UTC, newswangerd commented on src/loaders/standalone/standalone-loader.tsx
> +                <NavItem className={'nav-select'}>
Not a huge issue, but I the background behind the dropdown is highlighted when you mouse over it, which looks a little strange.

2020-09-10 07:46 UTC, ZitaNemeckova commented on src/containers/collection-detail/collection-content.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
I didn't do that because it would switch to default repo if I went to "no repo" page like Users.

2020-09-10 12:26 UTC, newswangerd commented on src/containers/collection-detail/collection-content.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
Oh, that's a good point. We need to solve this problem at some point, but we can figure it out later

2020-09-10 20:57 UTC, newswangerd requested changes
One last note: legacy routes such as http://localhost:8002/ui/newswangerd/collection-demo don't work on insights or standalone mode. I think this is probably because of the ordering on the routes.

2020-09-10 20:57 UTC, newswangerd commented on src/containers/collection-detail/collection-content.tsx
> +    if (DEPLOYMENT_MODE === Constants.STANDALONE_DEPLOYMENT_MODE) {
I found a way to do this on the loader. You can use `componentDidUpdate` and check to see if the current location is a match for a repository and compare it the repo that is stored in state.

```
  componentDidUpdate(prevProps) {
    const match = matchPath(this.props.location.pathname, {
      path: '/repo/:repo',
    });
    if (match && Constants.ALLOWEDREPOS.includes(match.params['repo'])) {
      const newRepoName = Object.keys(Constants.REPOSITORYNAMES).find(
        key => Constants.REPOSITORYNAMES[key] === match.params['repo'],
      );

      if (newRepoName !== this.state.selectedRepo) {
        this.setState({ selectedRepo: newRepoName });
      }
    }
  }
```

This also appears to solve the issue pages other than search would get stuck on repo/published

2020-09-10 20:57 UTC, newswangerd commented on src/loaders/standalone/standalone-loader.tsx
> +                      const originalRepo = this.state.selectedRepo;
repo toggle doesn't work on http://localhost:8002/ui/

2020-09-10 20:57 UTC, newswangerd commented on src/loaders/standalone/routes.tsx
>    routes = [
I want to figure out how to use a sub router to route the `repo/:repo` routes in the future. I don't think it's too hard to do. No need to worry about that now.

2020-09-11 12:51 UTC, newswangerd commented on src/api/collection.ts
> +    const path = '_ui/v1/repo/' + repo + '/';
use `this.getUIPath('repo')` instead of `_ui/v1/repo/`

2020-09-11 12:52 UTC, newswangerd commented on src/api/collection.ts
> +    const path = `_ui/v1/repo/${repo}/${namespace}/${name}/`;
use this.getUIPath('repo') instead of _ui/v1/repo/

2020-09-11 12:54 UTC, newswangerd commented on src/api/collection.ts
> +    const path = '_ui/v1/repo/' + repo + '/';
since we don't use `collections/` anymore you can change the `apiPath=this.getUIPath('repo/')` and use `apiPath` here

2020-09-11 17:57 UTC, newswangerd approved these changes

2020-09-11 18:01 UTC, merged