Add Small/LargeLogo component
ansible/ansible-hub-ui pull request #197
Opened 2020-09-21 09:16 UTC by ZitaNemeckova

Related to https://github.com/ansible/galaxy_ng/issues/465

### TODO:

#### Logos
- [ ] create a `LargeLogo` and `SmallLogo` component that import and display `'static/images/logo_large.svg'` and `'static/images/logo_small.svg'` respectively. 
- [ ] duplicate `static/images/galaxy_logo.svg` and rename it to `logo_small` and `logo_large` so that it gets used by default for both the large and small logos
- [ ] use `SmallLogo` on the masthead and `LargeLogo` on the login page

This will allow us to swap out the logos during the build process for the downstream RPMs to look like the mockups (at the bottom of this PR)

#### Add the following build time variables
- [ ] `NAMESPACE_TERM` -> this will replace all instances term "partner" with "namespace". Update the partners page, and partners url to use `NAMESPACE_TERM` instead of "partners". Set this to "namespace" for the standalone builds and "partner" for the insights builds.
- [ ] `APPLICATION_NAME` -> default this to `Galaxy NG`. This should be used for the app name on nave as well as the title in `index.html`

#### Navigation
- [ ] update the app navigation to look like the mockups bellow

#### Misc
- [ ] on the certification dashboard, change the phrase "certified" to "approved"
- [ ] on group management, rename the permissions to use more user friendly name and remove the `galaxy.` prefix. For example `galaxy.view_user` should display as `View user`

2020-09-25 14:42 UTC, newswangerd requested changes
You're missing the Application Name on the side bar
![Screen Shot 2020-09-25 at 10 42 06 AM](https://user-images.githubusercontent.com/6063371/94280781-d02c8580-ff1b-11ea-8142-26cb948b9952.png)
![Screen Shot 2020-09-25 at 10 40 52 AM](https://user-images.githubusercontent.com/6063371/94280782-d02c8580-ff1b-11ea-8e5e-bb273f3d1456.png)

2020-09-25 14:47 UTC, newswangerd commented
Certification dashboard still uses the term "certification". We need to rename this to approval. So the dashboard should be renamed to the "Approval Dashboard".

![Screen Shot 2020-09-25 at 10 46 00-fullpage](https://user-images.githubusercontent.com/6063371/94281353-82644d00-ff1c-11ea-93f6-f6ae916d747d.png)

2020-09-28 20:20 UTC, newswangerd requested changes

2020-09-28 20:20 UTC, newswangerd commented on src/loaders/standalone/standalone-loader.tsx
> +              <NavItem className={'nav-title'}>{APPLICATION_NAME}</NavItem>
I don't think `NavItem` is the right component for us to use here. `NavItem` causes the background to be highlighted and makes the application name look like a button, which is confusing. You might have to create your own CSS to make this work, it doesn't look like patternfly has the functionality we want here.

2020-09-29 15:33 UTC, ZitaNemeckova commented on src/loaders/standalone/standalone-loader.tsx
> +              <NavItem className={'nav-title'}>{APPLICATION_NAME}</NavItem>
@newswangerd Fixed so the nav title doesn't change apperance on hover and look like this
<img width="287" alt="Screenshot 2020-09-29 at 17 28 51" src="https://user-images.githubusercontent.com/9210860/94579647-5aa51a00-0279-11eb-9e4c-1c3214511642.png">

Does it look ok?

2020-09-29 15:34 UTC, newswangerd commented on src/loaders/standalone/standalone-loader.tsx
> +              <NavItem className={'nav-title'}>{APPLICATION_NAME}</NavItem>
Looks great!

2020-09-29 18:05 UTC, newswangerd approved these changes

2020-09-29 18:06 UTC, merged