[WIP] Add distribution and group permission checks
ansible/ansible-hub-ui pull request #209
Opened 2020-10-08 07:10 UTC by ZitaNemeckova

Related to https://github.com/ansible/galaxy_ng/issues/467

2020-10-19 20:29 UTC, newswangerd requested changes
Just missing remotes

2020-10-19 20:29 UTC, newswangerd commented on src/api/response-types/user.ts
>  export class Permissions {
Remote permissions are missing here. Need to hide the sync and edit remote option is if the user doesn't have permissions to edit remotes.

2020-10-20 10:10 UTC, ZitaNemeckova commented on src/api/response-types/user.ts
>  export class Permissions {
@newswangerd Done :)

2020-10-22 18:27 UTC, newswangerd approved these changes

2020-10-22 18:49 UTC, merged