[WIP] Add CLI config page
ansible/ansible-hub-ui pull request #230
Opened 2020-11-03 14:31 UTC by ZitaNemeckova

Closes-Issue: AHH-11

<img width="785" alt="Screenshot 2020-11-03 at 14 25 45" src="https://user-images.githubusercontent.com/9210860/97997658-7c01a480-1de9-11eb-89f3-0d4a8b5ff4ed.png">
<img width="1649" alt="Screenshot 2020-11-03 at 15 26 22" src="https://user-images.githubusercontent.com/9210860/97997674-7e63fe80-1de9-11eb-9b2d-0a431787b678.png">

2020-11-05 19:05 UTC, newswangerd commented
You can get rid of the Sync URL. Pulp fixed their URL config.

2020-11-05 19:05 UTC, newswangerd commented
Putting the CLI config in the list is really cramped. Is there any reason we can't put it in a modal?

2020-11-05 19:47 UTC, ZitaNemeckova commented
@newswangerd Agreed on it with Susan.

2020-11-09 15:41 UTC, newswangerd requested changes

2020-11-09 15:41 UTC, newswangerd commented on src/components/repositories/local-repository-table.tsx
> +            <ClipboardCopy isCode isReadOnly variant={'expansion'}>
This is kind of a mess and also an invalid configuration. This is what I'd recommend

```
    const cliConfig = [
      '[galaxy]',
      `server_list = ${distribution.repository.name}_repo`,
      '',
      `[${distribution.repository.name}_repo]`,
      `url=${getRepoUrl(distribution.base_path)}`,
      'token=<put your token here>',
    ];

[...]

    <ClipboardCopy isCode isReadOnly variant={'expansion'}>
      {cliConfig.join('\n')}
    </ClipboardCopy>
```

2020-11-09 15:41 UTC, newswangerd commented on src/components/repositories/local-repository-table.tsx
> +          title: 'Ansible CLI URL',
Let's rename this to "Repo URL"

2020-11-09 15:41 UTC, newswangerd commented on src/containers/token/token-insights.tsx
> +              {getRepoUrl('').replace('//', '')}
This is showing up as `https:ci.foo.redhat.com:1337/api/automation-hub/content//`, which is an invalid URL

2020-11-09 15:46 UTC, newswangerd commented on src/containers/token/token-insights.tsx
> +              {getRepoUrl('').replace('//', '')}
The correct URL should be `https://ci.foo.redhat.com:1337/api/automation-hub/`. Might need to update the `getRepoUrl` function to handle an empty repo string correctly

2020-11-09 19:55 UTC, newswangerd commented on src/components/repositories/local-repository-table.tsx
> +      `[${distribution.repository.name}_repo]`,
I screwed up. This should be `[galaxy_server.${distribution.repository.name}_repo]

2020-11-09 20:26 UTC, newswangerd requested changes

2020-11-09 20:26 UTC, newswangerd commented on src/containers/token/token-insights.tsx
> +              {getRepoUrl('').replace('//', '')}
this is still showing up as `https:ci.foo.redhat.com:1337/api/automation-hub/`

2020-11-10 13:37 UTC, newswangerd approved these changes

2020-11-10 13:39 UTC, merged