Can't see imports when there are more than 100 namespaces.
ansible/ansible-hub-ui pull request #2374
Opened 2022-07-25 08:24 UTC by MilanPospisil

https://issues.redhat.com/browse/AAH-1725

2022-07-26 13:40 UTC, MilanPospisil commented
Signing test seems to be broken also in master, seems like non related issue.

2022-08-08 19:42 UTC, newswangerd requested changes
Selecting a namespace with a collection on it seems to cause the filter to get cleared out.
![Screen Recording 2022-08-08 at 3 37 51 PM mov](https://user-images.githubusercontent.com/6063371/183500903-840c4d09-47ae-4b2c-9288-b31163ef262a.gif)

2022-08-08 19:42 UTC, newswangerd commented on src/components/my-imports/import-list.tsx
> +    MyNamespaceAPI.list({ page_size: 100, keywords: namespace_filter })
lets limit the page size to 10

2022-08-09 11:46 UTC, MilanPospisil commented on src/components/my-imports/import-list.tsx
> +    MyNamespaceAPI.list({ page_size: 100, keywords: namespace_filter })
Thanks for catching that. The selection based on filter of loaded namespaces was not good idea, now it select exactly what it is in the params.

2022-08-17 22:35 UTC, himdel commented on src/components/my-imports/import-list.tsx
> +      .catch((result) => console.log(result));
console.log .. this should be an alert?

2022-09-19 11:14 UTC, himdel commented
`src/containers/my-imports/my-imports.tsx:121` is missing the new `addAlert` prop for `ImportsFilter`,
otherwsie LGTM :)

2022-09-21 09:09 UTC, MilanPospisil commented
> 

I noticed it, however Im not sure how it happened... Meanwhile, I repaired one error - when search ahead text was empty, it passed API call with filter undefined, rather empty string - this causes no namespaces returned (unless prefixed by undefined :-) ).

2022-09-22 11:36 UTC, himdel commented
When visiting `/ui/my-imports` directly, previously this would open the first namespace, now none is selected.
That's OK, the left side message looks good, but the right side keeps spinning in such case:

![20220922113446](https://user-images.githubusercontent.com/289743/191736298-b1a67e69-4c3d-4101-943b-c515270dc2e8.png)

^ can probably be fixed by using the same ``importDetailError: t`No data`,`` logic that's used when a namespace has no imports.

(

![20220922113218](https://user-images.githubusercontent.com/289743/191736510-5285c297-1903-4cce-9840-0209c24efb73.png)

)

2022-09-22 11:39 UTC, himdel commented
When I unselect a namespace (using the :x: button in the namespace selector), it still triggers a `/api/automation-hub/_ui/v1/collection-versions/?namespace=null&name=null&version=null&offset=0&limit=10` (note the `null`s) request.

And somehow the right side ends up displaying some previous value:

![20220922113247](https://user-images.githubusercontent.com/289743/191737073-5424a104-bfd1-46f8-8e74-b4bbb4289a71.png)

2022-09-23 10:38 UTC, MilanPospisil commented
You are right, I forgot to handle empty namespace selection. The app would still work, but it will not look proffesional. I fixed it now.

2022-09-26 23:53 UTC, himdel commented on src/containers/my-imports/my-imports.tsx
> +    empty = this.state.params.namespace ? true : false;
unused

2022-09-26 23:53 UTC, himdel commented on src/containers/my-imports/my-imports.tsx
> +                  empty={this.state.params.namespace ? false : true}
```suggestion
                  empty={!this.state.params.namespace}
```

2022-09-27 00:23 UTC, himdel commented
Just the 2 changes ^ to make linter checks happy, otherwise LGTM :+1:

2022-09-27 14:49 UTC, merged