Remove counter from collection signing UI
ansible/ansible-hub-ui pull request #2414
Opened 2022-08-03 20:06 UTC by ShaiahWren

Issue: AAH-1852

Connected to https://issues.redhat.com/browse/AAH-1794

Unfortunately, I am unable to take show before and after shots this change - running the signing steps does not work for me. The reviewer can contact me to go over the steps for seeing the signing/filter.

1. Feed your local system with some collections
2. Add to your .compose.env the settings: 
ENABLE_SIGNING=1
PULP_GALAXY_COLLECTION_SIGNING_SERVICE='ansible-default'
PULP_GALAXY_REQUIRE_CONTENT_APPROVAL=true
PULP_GALAXY_AUTO_SIGN_COLLECTIONS=true
3. Run: ./compose exec api ./entrypoint.sh manage create-test-collections --strategy=faux --ns=1 --cols=10 --prefix=signing
4. Then you can go to approval dashboard and approve & sign some collections
![Screenshot_2022-08-02_19-22-54](https://user-images.githubusercontent.com/64337863/182699319-8a7479c4-8f37-47b4-be19-b93b319069de.png)
![Screenshot_2022-08-02_19-27-30](https://user-images.githubusercontent.com/64337863/182699323-28727ebc-e1b8-458c-aa9d-46d0bc76370f.png)
5. browse http://0.0.0.0:8002/ui/repo/published and http://0.0.0.0:8002/ui/repo/staging and check if the badges are showing ok

2022-08-08 19:16 UTC, newswangerd commented
/retest

2022-08-08 19:26 UTC, newswangerd requested changes

2022-08-08 19:26 UTC, newswangerd commented on CHANGES/1852.bug
> +Remove signature counter and partially signed filter from UI.
lets chance this to .misc.

2022-08-08 19:26 UTC, newswangerd commented on src/components/signing/sign-all-certificates-modal.tsx
> +      title={t`Sign collection`}
If I'm not mistaken, this is still going to sign all the collections, not the latest version (right @rochacbruno ?)

The only thing is we no longer get an easy count of the number of signed and unsigned collections here. You might be able to make an api request to a different set of apis to get this information. If that's not possible, then we should adjust the wording to reflect that you're still signing all the collections, but remove any reference to how many versions are getting signed.

2022-08-09 13:58 UTC, rochacbruno commented on src/components/signing/sign-all-certificates-modal.tsx
> +      title={t`Sign collection`}
YEs if it is on the namespace view it is signing all collections under the namespace

2022-08-10 18:12 UTC, newswangerd approved these changes

2022-08-10 18:12 UTC, newswangerd commented
/retest

2022-08-11 15:02 UTC, merged