Add tooltips to user's password field and fixes namespace's to PF version
ansible/ansible-hub-ui pull request #266
Opened 2020-12-01 14:12 UTC by ZitaNemeckova

Closes-Issue: AAH-159

**NAMESPACE CREATE FORM**
Before:
<img width="1250" alt="Screenshot 2020-12-01 at 15 09 27" src="https://user-images.githubusercontent.com/9210860/100751108-397eb800-33e7-11eb-84e6-3c3d450e550e.png">

After:
<img width="1220" alt="Screenshot 2020-12-01 at 14 45 35" src="https://user-images.githubusercontent.com/9210860/100750898-f3295900-33e6-11eb-94e7-810b915fa3f6.png">

**USER CREATE FORM**
Before:
<img width="245" alt="Screenshot 2020-12-01 at 15 08 30" src="https://user-images.githubusercontent.com/9210860/100751005-181dcc00-33e7-11eb-9649-990b83d7c0c4.png">

After:
<img width="326" alt="Screenshot 2020-12-01 at 14 55 48" src="https://user-images.githubusercontent.com/9210860/100750905-f6244980-33e6-11eb-82c3-3e9b2220eec4.png">

Used password validators:
```
class MinimumLengthValidator(min_length=8)¶
Validates whether the password meets a minimum length. The minimum length can be customized with the min_length parameter.

class UserAttributeSimilarityValidator(user_attributes=DEFAULT_USER_ATTRIBUTES, max_similarity=0.7)¶
Validates whether the password is sufficiently different from certain attributes of the user.

The user_attributes parameter should be an iterable of names of user attributes to compare to. If this argument is not provided, the default is used: 'username', 'first_name', 'last_name', 'email'. Attributes that don’t exist are ignored.

The minimum similarity of a rejected password can be set on a scale of 0 to 1 with the max_similarity parameter. A setting of 0 rejects all passwords, whereas a setting of 1 rejects only passwords that are identical to an attribute’s value.

class CommonPasswordValidator(password_list_path=DEFAULT_PASSWORD_LIST_PATH)¶
Validates whether the password is not a common password. This converts the password to lowercase (to do a case-insensitive comparison) and checks it against a list of 20,000 common password created by Royce Williams.

The password_list_path can be set to the path of a custom file of common passwords. This file should contain one lowercase password per line and may be plain text or gzipped.

class NumericPasswordValidator¶
Validates whether the password is not entirely numeric.
```
from https://docs.djangoproject.com/en/3.1/topics/auth/passwords/

2020-12-01 14:17 UTC, ZitaNemeckova commented
@sbuenafe-rh @fionayhlin What do you think about wording of password tooltip? Any suggestions to make it better? Thanks :)
<img width="326" alt="Screenshot 2020-12-01 at 14 55 48" src="https://user-images.githubusercontent.com/9210860/100750905-f6244980-33e6-11eb-82c3-3e9b2220eec4.png">

2020-12-01 17:08 UTC, sbuenafe-rh commented
@ZitaNemeckova I would use the popover component (white bkg) with the info icon. I would also format at least the password requirements in a bulleted list (see screenshot below). We can run the text copy by @cbudz for better wording. 

<img width="1093" alt="Screen Shot 2020-12-01 at 11 50 20" src="https://user-images.githubusercontent.com/43220036/100772378-7b9b0000-33cd-11eb-84e7-420f0821a5ff.png">

2020-12-01 17:32 UTC, cbudz commented
Hey @ZitaNemeckova and @sbuenafe-rh -Does the password field support special characters? Also if it doesn't validate against what's up there about user attributes and common passwords i'd just say you can have one or two simple and prescriptive sentence like "Create a password using at least 9 characters, including special characters <or list of supported special characters>, ex <x!!f3@pl$%>. Avoid using common names or expressions.

2020-12-01 18:33 UTC, newswangerd requested changes
This is a good start, but there are still a lot of other confusing fields that need helper texts.

2020-12-01 18:33 UTC, newswangerd commented on src/components/user-form/user-form.tsx
> +                      Password must contain at least 9 characters. Password
Can this be formatted like a list?

2020-12-01 18:33 UTC, newswangerd commented on src/components/namespace-modal/namespace-modal.tsx
> +                  'Namespace names are limited to lowercase word characters ([a-zA-Z0-9_]), must have a minimum length of 2 characters and cannot start with an ‘_’.'
instead of `([a-zA-Z0-9_])` we should just say "alphanumeric characters and underscores".

2020-12-01 18:33 UTC, newswangerd commented on src/components/namespace-modal/namespace-modal.tsx
> +              <Tooltip
I think we should create a `HelperText` component that just take the text to display. That way whenever we want to add helper texts to forms we can just do

```
<HelperText>This is how you do the thing.</HelperText>
```

Instead of
```
<Tooltip position={...} content={}>
<Icon/>
</Tooltip>
```

2020-12-02 15:06 UTC, newswangerd commented
Notes from the meeting today:

Use popovers and not tooltips.

- upload collection form: explain character requirments
- namespace form:
  - useful links
    - change name to related links
  - logo url: link to image, size requirements, file types etc

- User form:
  - Username - any validation requirments
  - Password - validation requirments
  - group create - validation for name

- Edit group permissions form
  - add desciption text underneath permission fields
    - add for all fields
  - also rename modify ansible repo content to something that makes more sense

- remote form
  - add popovers for everything except name
  - use a wider modal for this

2020-12-02 15:07 UTC, ZitaNemeckova commented
@sbuenafe-rh @cbudz updated as you suggested. Please have a look that it's ok, thank you :)

2020-12-03 14:24 UTC, ZitaNemeckova commented
@newswangerd this is ready for another round of review :) Other tooltips/popups will be added in a followup PR.

2020-12-03 14:56 UTC, newswangerd approved these changes

2020-12-03 14:56 UTC, newswangerd commented on src/components/helper-text/helper-text.tsx
> +  content: string;
You don't have to do this, but if you change the prop name to `children` you can pass it in as `<HelperText>foo</HelperText> instead of `<HelperText content='foo' />`. Both are fine and you don't need to change this, but i just wanted to call this out.

2020-12-04 07:56 UTC, merged