docker test runner
ansible/ansible-hub-ui pull request #283
Opened 2020-12-18 17:11 UTC by ironfroggy

Thank you for a new Pull Request!

Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ansible/ansible-hub-ui/blob/master/developer_guidelines.md

Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.

Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description as necessary to get the reviewer up to the same domain knowledge level as yourself
* Keep code changes as short as possible and implementing a single feature/fix/refactoring, when possible

Links [Optional]
----------------

* http://documentation.for/library/that/I/am/adding
* [PR relevant issue or pull_request](#123)

Steps for Testing/QA [Optional]
-------------------------------

If there are any manual steps that you would like the reviewer(s) to take to verify your changes, please describe in detail the steps to reproduce the features added by the pull request, or the bug before and after the change.

2021-01-11 18:56 UTC, hendersonreed commented on test/cypress/integration/repo_management.js
> +            cy.visit(`${scheme}://${host}/ui/repositories?page_size=10&tab=remote`);
Is the 'url' argument really needed? On my end it was causing problems, which were resolved by simply eliminating it and using `$host` on line 14, like:

```
cy.visit(`${host}/ui/repositories?page_size=10&tab=remote`);
```

2021-01-11 20:08 UTC, ironfroggy commented on test/cypress/integration/repo_management.js
> +            cy.visit(`${scheme}://${host}/ui/repositories?page_size=10&tab=remote`);
this must have come up with some situation I had between HTTP/HTTPS URLs. I'll try to identify where that came from, and if I can't find a specific thing I was trying to work around then I'll use `host` directly.

2021-01-11 21:02 UTC, newswangerd requested changes
It would be great if you could add a note to the README explaining out how to run the container for cypress.

2021-01-11 21:02 UTC, newswangerd commented on test/Dockerfile
> +ENV CYPRESS_HOST="localhost:8002"
Also worth noting that the values you have here aren't the defaults for our dev environment. We use password=admin and prefix=/api/automation-hub/

2021-01-12 20:25 UTC, newswangerd commented
I noticed today that if I have node_modules in the tests directory that I get this error when running the containerized tests from the iqe project. Removing node_modules seems to have fixed the issue.

```
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /root/.cache/Cypress/4.11.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
```

2021-01-12 20:27 UTC, hendersonreed commented
I've had the same issue - currently we're mounting the ansible-hub-ui directory into the container that's used to run the tests, which I think is the cause of this. I think @ironfroggy is currently working on a solution.

2021-01-14 14:52 UTC, ironfroggy commented on test/Dockerfile
> +ENV CYPRESS_HOST="localhost:8002"
Thanks I updated these, this was stuff I'd changed in my own local VM config and forgot wasn't the default

2021-02-09 21:13 UTC, newswangerd commented on package.json
> +        "test-build": "test/scripts/ctn-build.sh",
These scripts don't seem to exist.

2021-02-09 21:48 UTC, newswangerd reviewed
this creates a new `test/scripts/..test/` directory, which seems like a typo. A bunch of files got included under that path that shouldn't be committed.

- test/scripts/..test/cypress/videos/group_management.js.mp4
- test/scripts/..test/cypress/videos/menu.js.mp4
- test/scripts/..test/cypress/videos/repo_management.js.mp4
- test/scripts/..test/cypress/videos/user_dashboard.js.mp4

2021-02-09 21:48 UTC, newswangerd commented on .gitignore
> +coverages
mine creates a folder called coverage not coverages

2021-02-09 21:48 UTC, newswangerd commented on .gitignore
> +coverages
mine created a `coverge` dir, not a `coverages` dir

2021-02-09 21:48 UTC, newswangerd commented on test/scripts/ctn-run.sh
> +HUB_SERVER=${HUB_SERVER:-"localhost:8002"}
I keep getting a `Error: connect ECONNREFUSED 127.0.0.1:8002` error message. I tried changing the server to something else, but it seems like it's ignoring the configuration.

Here's more logs:
```
[cypress-log-to-output] Attempting to connect to Chrome Debugging Protocol
[cypress-log-to-output] Connected to Chrome Debugging Protocol
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-02-09T21:42:55" tests="0" file="cypress/integration/user_dashboard.js" failures="0" time="0">
  </testsuite>
  <testsuite name="Hub User Management Tests" timestamp="2021-02-09T21:42:55" tests="1" failures="1" time="0">
    <testcase name="Hub User Management Tests &quot;before each&quot; hook for &quot;User table lists users&quot;" time="0" classname="&quot;before each&quot; hook for &quot;User table lists users&quot;">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8002/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:8002

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Hub User Management Tests`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8002/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8002

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
 ```

2021-02-09 21:48 UTC, newswangerd commented on test/scripts/ctn-run.sh
> +HUB_SERVER=${HUB_SERVER:-"localhost:8002"}
I tried to set the URL to localhost:5001 and didn't have any luck.

2021-02-10 14:08 UTC, ironfroggy commented on .gitignore
> +coverages
i think that was an accidental edit or rebase mistake

2021-02-10 21:49 UTC, ironfroggy commented on test/scripts/ctn-run.sh
> +HUB_SERVER=${HUB_SERVER:-"localhost:8002"}
OK, I found some mistakes in how I was getting configuration into the container, especially in trying to get both the cypress.env.json and environment variables in so they can properly overwrite. It should be working now when you change settings through either mechanism 🤞

2021-02-18 20:35 UTC, newswangerd commented on test/scripts/ctn-run.sh
> +	-e HUB_UPLOAD_TO_INBOUND \
please add `--rm` so that this doesn't clutter the system with dead containers.

2021-02-18 20:38 UTC, ironfroggy commented on test/scripts/ctn-run.sh
> +	-e HUB_UPLOAD_TO_INBOUND \
😬 whoops!

2021-02-18 21:03 UTC, newswangerd approved these changes
PR looks good. I can't run this on my machine for some reason. Going to defer to @ZitaNemeckova and @hendersonreed for further testing until I can sort out whatever is wrong with my machine

2021-02-19 19:29 UTC, hendersonreed commented
Pushed a few commits that resolved some errors I was seeing on my side, now everything passes both in and out of the docker container! @newswangerd @ZitaNemeckova we'd love your review on this when you get the chance. If it works, then we'll merge it in.

2021-03-10 02:33 UTC, merged