Add Pupl API to UI
ansible/ansible-hub-ui pull request #288
Opened 2021-01-12 14:33 UTC by ZitaNemeckova

Closes-Issue: AAH-255

2021-01-19 12:23 UTC, ZitaNemeckova commented
@newswangerd please have a look, thanks :)

2021-01-19 15:49 UTC, newswangerd requested changes
Just need to DRY out the pulp api base.

2021-01-19 15:49 UTC, newswangerd commented on src/api/pulp.ts
> +  list(params?: object, apiPath?: string) {
These are all copy pasted from BaseAPI. They should really be moved to a reusable file or inherited from a shared base class.

I know we were attempting to not change the base class for the full API, but I think it should be fairly easy to make a new base class that contains the `list`, `get`, `update`, `create`, `delete`, `patch`, `getPath`, `authHandler` and `mapPageToOffset` methods ad the `apiPath` and `http` properties without introducing any regressions.

You could also just move the shared methods to an `api.utils` module and import them here. That might be a little bit easier, but I think it's not quite as clean.

2021-01-19 15:49 UTC, newswangerd commented on src/api/execution-environment.ts
> +export const ExecutionEnvironmentAPI = new API();
I like the idea of just putting all EE related calls into a single module rather than presenting the different objects in the pulp API to the presentation layer. I'm curious to see how this will work in the final implementation,

2021-01-19 15:55 UTC, newswangerd commented on src/api/execution-environment.ts
> +export const ExecutionEnvironmentAPI = new API();
One problem you might run into is that page loading will be blocked until all the APIs resolve. This is probably fine for details, but I know on the list views we'll have to make a call for each container to get the description, and that could slow down the list page a lot. If the APIs are called separately you could use a skeleton to show that the description is still loading: https://patternfly-react.surge.sh/components/skeleton. If all the descriptions are grabbed asynchronously, latency might not be an issue though.

2021-01-19 16:00 UTC, newswangerd commented on src/api/pulp.ts
> +    this.apiPath = this.apiBaseURL;
I'm surprised these calls work without the CSRF token getting set. I guess it probably gets set by the other API calls and reused here. At any rate, it might be worth adding the `authHandler` here.

2021-01-22 15:24 UTC, newswangerd requested changes

2021-01-22 15:24 UTC, newswangerd commented on src/api/base.ts
> +      baseURL: this.apiBaseURL(),
I would recommend passing this as a constructor argument instead of getting it from some function that you then have to override.

2021-01-22 15:24 UTC, newswangerd commented on src/api/base.ts
> -    return `_ui/${this.UI_API_VERSION}/${url}`;
This function isn't necessary for anything other than the hub endpoints, so you can remove it here and just provide it in the hub base class.

2021-01-22 15:24 UTC, newswangerd commented on src/api/pulp.ts
> +    delete params['sort'];
I would recommend moving `mapPageToOffset` to the base class and overriding the `list` method on the pulp class here to provide the mapping between ordering and sort.

Messing with `sort` in this function is kind of an unexpected side effect and this also makes it so that the actual code for the `mapPageToOffset` function is still duplicated in two places.

2021-01-26 15:27 UTC, newswangerd approved these changes

2021-01-26 16:01 UTC, merged