[WIP] Execution Environment List page
ansible/ansible-hub-ui pull request #290
Opened 2021-01-15 14:55 UTC by ZitaNemeckova

TODO:
- [ ] filter
- [ ] sort
- [ ] description?
- [ ] cretaed
- [ ] name
- [ ] pagination works

2021-01-19 13:11 UTC, ZitaNemeckova commented
@sbuenafe-rh I have no "Last modified" date. What do you think?

2021-01-19 14:06 UTC, sbuenafe-rh commented
> @sbuenafe-rh I have no "Last modified" date. What do you think?
We don't have data for the container repository activity? any pulls or pushes?

Also, could the container repository list be defaulted to alpha order?

2021-01-28 14:43 UTC, newswangerd requested changes

2021-01-28 14:43 UTC, newswangerd commented on src/containers/execution-environment-list/execution_environment_list.tsx
> +                          this.updateParams(p, () => this.queryEnvironments())
This should set the page to 1 before querying the environments. Otherwise if you perform a search when you're on page 2, it will stay on page 2 and not return anything

2021-01-28 14:43 UTC, newswangerd commented on src/containers/user-management/user-list.tsx
> +import { UserAPI, UserType, ExecutionEnvironmentAPI } from '../../api';
what's this doing here?

2021-01-28 14:43 UTC, newswangerd commented on src/api/pulp.ts
> +    return this.http
code that's specific to execution environments should go in an execution environment module. We're going to be using the pulp api base class for other endpoints too.

2021-01-28 15:11 UTC, newswangerd requested changes

2021-01-28 15:11 UTC, newswangerd commented on src/containers/execution-environment-list/execution_environment_list.tsx
> +        <td>{item.name}</td>
this should be `base_path` instead of name.

2021-01-28 15:11 UTC, newswangerd commented on src/containers/execution-environment-list/execution_environment_list.tsx
> +  items: any[];
There should be a type for the items instead of any. Most of our types are stored in api/api-responses/

2021-02-02 14:43 UTC, newswangerd approved these changes
Feel free to merge this once you change the containers path.

2021-02-02 14:43 UTC, newswangerd commented on src/paths.ts
> +  executionEnvironments = '/execution-environments',
Change this to `/containers/`

2021-02-02 14:54 UTC, ZitaNemeckova commented on src/paths.ts
> +  executionEnvironments = '/execution-environments',
Fixed :)

2021-02-02 15:06 UTC, merged