[WIP] Container detail page
ansible/ansible-hub-ui pull request #304
Opened 2021-02-16 13:35 UTC by ZitaNemeckova

TODO:
- [ ] Detail tab - README editor and display
- [ ] Activity tab
- [ ] Activity table
- [ ] Heat map
- [ ] Instructions
- [ ] Images tab/table
- [ ] API

2021-03-01 15:38 UTC, sbuenafe-rh commented
@ZitaNemeckova on the header there should be an **Edit** button (to edit the repo). The description should be place in a tooltip (black bkg). 

I'll look into the ReadMe empty state message and button placement. But for the time being, I don't believe you need the "Please add README" text above the Save & Cancel action buttons.

2021-03-02 09:59 UTC, ZitaNemeckova commented
@sbuenafe-rh Thanks for review :) I want to add Edit button with a modal form in followup PR to make it easier to review codewise.

2021-03-02 14:43 UTC, sbuenafe-rh commented
@ZitaNemeckova tooltip looks good! thanks for the note on the other Edit button with modal. I'll try to draft up an empty state message for the readme.

2021-03-23 19:54 UTC, himdel commented on src/components/markdown-editor/markdown-editor.scss
> +    // I don't know why, but just setting width causes this element to get
would `flex-shrink: 0` help? Sounds like this is caused by flexbox treating width as the optimum, not a constraint.

2021-03-23 22:27 UTC, himdel commented on src/components/namespace-form/resources-form.tsx
> +    console.log('Data: ' + data);
console log (and the comment on line 73?)

2021-03-23 22:28 UTC, himdel commented on src/components/markdown-editor/markdown-editror.tsx
> +import * as React from 'react';
editror -> editor (in the filename)

2021-03-23 22:28 UTC, himdel commented on src/components/index.ts
> +export { MarkdownEditor } from './markdown-editor/markdown-editror';
editor

2021-03-24 00:25 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    this.setState({ loading: false });
unlikely to be true at this point?

2021-03-24 00:26 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +        console.log(result);
console.log

2021-03-24 00:29 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    this.setState({ loading: false });
and you have an ordering problem here.. even without this line, the *first* query* request to complete will reset loading to false, not the last one ... may need 3 separate loading vars, or one method that deals with all the requests and sets state accordingly

2021-03-24 00:30 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  container: any;
`container: { name: string; };` ?

2021-03-24 00:32 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                description={'Add README file by using RAW MAkdown editor'}
MAkdown -> Markdown

2021-03-24 00:33 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                  this.state.markdownEditing ? 'Here goes README' : ''
Here goes Johnny :) .. I guess this one may not be intential? :)

2021-03-24 00:36 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                  updateParams={() => {}}
intentionally not resortable?

2021-03-24 00:38 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            updateParams={() => console.log('update params and queryImages')}
console log / TODO?

2021-03-24 00:39 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            <Label variant='outline' icon={<TagIcon />}>
missing key?

2021-03-24 00:40 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +          let image = pickBy(object, function(value, key) {
is this `let image = pick(object, ['digest', 'tags', 'pulp_created']);`?

2021-03-24 00:44 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            count={this.state.images.length}
does the API return `meta.count` for images? Giving the same count as the number of loaded images means no pagination ever, if the number of loaded images depends on items per page.

2021-03-24 00:44 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            count={this.state.images.length}
(and here, `meta.count`)

2021-03-24 09:50 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                  updateParams={() => {}}
Yes. API is not able to sort or filter activities right now.

2021-03-24 10:25 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            updateParams={() => console.log('update params and queryImages')}
yep, fixed :)

2021-03-24 10:56 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    this.setState({ loading: false });
Fixed :)

2021-03-24 12:54 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    this.setState({ loading: false });
Nice :) except now the query* calls from buttons won't unset loading..

2021-03-24 19:41 UTC, newswangerd requested changes

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                description={'Add README file by using RAW Makdown editor'}
Lets rephrase this to "Add a README with instructions for using this container."

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            <ClipboardCopy isCode isReadOnly variant={'expansion'}>
Don't use `isCode` here.

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +              Instructions
Maybe change this to "Pull this image"?

"Instructions" is so vague.

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +              {instructions}
Same as with the images page: the command has to have the registry host in it

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +          {params['tab'] === 'detail' && this.renderDetail()}
This component needs to be split up into 3 components, one for each tab. Putting all the logic into one component makes it very difficult to find things and figure out what's happening.

Additionally, each tab should have it's own URL route, just like we do for collection details.

I would recommend the following routing
- `containers/<name>/` -> Detail
- `containers/<name>/_content/activity/` -> Activity
- `containers/<name>/_content/images/` -> Images

The reason for  `_content` is because we have to route urls for `containers/<name>/` and `containers/<namespace>/<name>/`, but `_content` isn't a valid docker image name, so that avoids any potential routing conflicts between our routes and the container names.

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  renderActivity() {
Lets add a "Load more" link at the bottom of the list of activities that loads the next "page". As you've pointed out, using pagination here doesn't really work because there isn't a 1 to 1 relationship between rows here and API responses. Load more would solve this by just requesting the next page of activity and appending it to the bottom of the table.

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  images: any[];
Don't use `any`. Need to add types for the api responses for images, container, and activities.

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +          title: 'Image',
Rename this to "Digest"

2021-03-24 19:41 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +            <Label color='blue'>{image.digest.slice(0, 8)}</Label>
I'd recommend `{image.digest.split(':')[0]:image.digest.split(':')[1].slice(0, 8)}`.

That way you always get the digest type and at least 8 digits of the actual digest.

2021-03-24 19:49 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  renderActivity() {
Actually, can you create an issue for this instead? Lets tackle this in a different PR

2021-03-25 14:06 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  renderActivity() {
https://issues.redhat.com/browse/AAH-461

2021-03-29 11:25 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +                  Edit
Tracking via https://issues.redhat.com/browse/AAH-467

2021-03-29 14:37 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +      params: {
This still isn't working. The parameters are in the URL, but they don't get added to the filter when you load the page.

2021-03-29 14:54 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +      'podman pull localhost:5001/' + this.state.container.name + ':latest';
Don't hardcode the URL into the podman pull instructions. Use the URL from the browser.

2021-03-29 14:54 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +        <BaseHeader
Since the header is the same across all the EE pages, it would be wise to create one component with the shared information that can be used across all the pages.

2021-03-29 14:54 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    const description = '';
Description should be available from the API.

2021-03-29 14:54 UTC, newswangerd commented on src/paths.ts
> +  executionEnvironmentDetailActivities = '/containers/:container/_content/activity',
All these routes need to match `/containers/:container/` and `/container/:container/:namespace/`

2021-03-29 14:54 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  images: any[];
This still needs to be fixed.

2021-03-29 14:54 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +        <td>{image.size}</td>
This still needs to be fixed

2021-03-29 15:01 UTC, newswangerd requested changes

2021-03-31 10:15 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +      'podman pull localhost:5001/' + this.state.container.name + ':latest';
Not sure if it's correct given I hardcode change of ports.

2021-03-31 10:25 UTC, ZitaNemeckova commented on src/api/activities.ts
> +    return this.http.get(this.apiPath + id + '/_content/history/');
Ok, but there's no pagination for now as UI is parsing the data and it's not one to one.

2021-03-31 13:42 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail_activities.tsx
> +                updateParams={p => this.setState({ redirect: p.tab })}
To be fixed later. Tracker https://issues.redhat.com/browse/AAH-477

2021-04-07 15:59 UTC, newswangerd approved these changes
There are still a few things here that violate best practices, which will make updating and debugging this page later more challenging. However, in the interest of finishing this feature, I'm going to mark this approved and take it on as technical debt for later.

2021-04-07 15:59 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    if (this.state.redirect === 'activity') {
This should be moved into the header.

2021-04-07 15:59 UTC, newswangerd commented on src/components/execution-environment-header/execution-environment-header.tsx
> +    ExecutionEnvironmentAPI.get(this.props.id)
Components should never make API calls unless it's absolutely necessary to do so.

2021-04-07 15:59 UTC, newswangerd commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +  container: { name: string };
This should use a container type that gets imported from `api/response-types`, especially since this type is used on all the container detail views as well as the container list view.

2021-04-08 10:04 UTC, merged