[WIP] Repository form
ansible/ansible-hub-ui pull request #313
Opened 2021-03-03 13:54 UTC by ZitaNemeckova

2021-04-13 16:36 UTC, newswangerd commented on src/api/base.ts
> +    console.log('PATCH');
Don't forget to remove these

2021-04-13 21:56 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +              availablePermissions={[
would `Object.keys(GROUP_HUMAN_RESOURCES).filter((key) => key.startsWith('container.'))` make sense here, instead of copying the list?

2021-04-13 23:59 UTC, himdel commented
We should move the button from execution-environment-header to the top of the Detail tab, similar to https://github.com/ansible/ansible-hub-ui/pull/317.

Unless the idea is for the Edit button to work in all the tabs?

2021-04-14 00:06 UTC, himdel commented on src/components/execution-environment-header/execution-environment-header.tsx
> +            {' '}
the space before and after edit is probably not needed?

2021-04-14 00:08 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +          <FormGroup key='groups' fieldId='groups' label='Groups with access'>
expanding the select doesn't actually appear to do anything until you scroll down

it looks like setting a z-index doesn't work because the select options can't escape the grid made by the form (?) - is this solved anywhere?

(Or, `padding-bottom: 3em` works, if we don't have a handy info message to put there for padding :))

2021-04-14 00:16 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +      availableGroups: [],
something is wrong here .. I don't see code to set availableGroups, or to use them
and the value in selectedGroups doesn't end up selected

Is the idea to just select a group to edit, without that selection meaning anything else?

Also, I can select the same group multiple times, but deleting one deletes all of them.

2021-04-14 00:19 UTC, himdel commented on src/constants.tsx
> +    'container.change_containerdistribution': 'Change',
the last 5 buttons are probably missing "distribution" ?

2021-04-14 00:23 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +          <FormGroup key='groups' fieldId='groups' label='Groups with access'>
(also the select is a bit too wide for the trash icon to fit on the same line)

2021-04-14 00:24 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +              promises.push(
(you can just `const promises = [ ContainerDis..., Exec... ];`)

2021-04-14 00:25 UTC, himdel commented on src/api/container-distribution.ts
> +  constructor() {
(a constructor just calling super is exactly what you inherit if you don't mention a constructor)

2021-04-14 08:12 UTC, ZitaNemeckova commented on src/components/execution-environment/repository-form.tsx
> +      availableGroups: [],
`ObjectPermissionField` conponent is handling the loading of available groups. The multiselection of same groups is known bug that we should fix.

Created https://issues.redhat.com/browse/AAH-501

2021-04-14 08:44 UTC, ZitaNemeckova commented on src/components/execution-environment/repository-form.tsx
> +              availablePermissions={[
Moved to Constants.

2021-04-14 14:06 UTC, himdel commented
From the UX meeting...

* we can make the modal wider, that should help with the permission select styling and the trash icon
* there's a way for the select to expand over the modal .. https://github.com/ansible/ansible-hub-ui/blob/master/src/components/namespace-modal/namespace-modal.tsx#L151
* unify on "container" vs "execution envrionment" in the list of privileges (probably "container")
* remove some of the privileges

(A redesign of those components/dropping the modal can come later.)

---

Also, "Description" doesn't seem to get saved, and isn't displayed anywhere?

2021-04-14 19:04 UTC, newswangerd commented on src/api/base.ts
> +    console.log(apiPath || this.apiPath);
console.log

2021-04-15 15:56 UTC, ZitaNemeckova commented on src/components/execution-environment/repository-form.tsx
> +      availableGroups: [],
And you solved it :D

2021-04-15 17:53 UTC, newswangerd requested changes

2021-04-15 17:53 UTC, newswangerd commented on src/components/execution-environment/repository-form.tsx
> +            onClick={() => onSave(description, selectedGroups)}
onSave should reload the container that's displayed in the header after a successful save is complete.

2021-04-15 17:53 UTC, newswangerd commented on src/constants.tsx
> +    'namespace_view_containerdistribution',
Remove `namespace_view_containerdistribution`. That's for viewing private repos.

2021-04-15 17:53 UTC, newswangerd commented on src/components/execution-environment/repository-form.tsx
> +            <TextInput
disable this field if the user doesn't have `container.namespace_change_containerdistribution` permissions.

2021-04-15 17:53 UTC, newswangerd commented on src/components/execution-environment/repository-form.tsx
> +            <ObjectPermissionField
Disable this field if the user doesn't have `container.change_containernamespace` permissions.

2021-04-15 17:53 UTC, newswangerd commented on src/containers/execution-environment-detail/base.tsx
> +                onSave={(description, selectedGroups) => {
Don't send API request for fields the user hasn't changed. This will prevent things from breaking if the user has permissions to update the description but not the groups.

2021-04-15 17:53 UTC, newswangerd commented on src/containers/execution-environment-detail/base.tsx
> +                  Promise.all(promises).then(() =>
There's no error handling here. If the user submits an invalid request, the form just hangs.

2021-04-15 21:22 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +      availableGroups: [],
Yup, `availableGroups` is dead in that case :)

2021-04-15 21:23 UTC, himdel commented on src/constants.tsx
> +    'container.add_containernamespace': 'Create new execution environments',
these are still a mix of "execution environment" and "container"

2021-04-16 12:21 UTC, himdel commented on src/containers/execution-environment-detail/base.tsx
> +          ExecutionEnvironmentNamespaceAPI.get(result.data.namespace.name).then(
return, so that we catch errors with the catch on line 208?

2021-04-16 12:24 UTC, himdel commented on src/containers/execution-environment-detail/base.tsx
> +      return TaskAPI.get(task).then(async result => {
then + async function is a werid combination.. what about..?

```js
return TaskAPI.get(task).then((result) => {
  if (result.data.state !== 'completed') {
    return new Promise(r => setTimeout(r, 500).then(() => this.waitForTask(task));
  }
});
```

2021-04-16 12:51 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +              isDisabled={this.props.permissions.includes(
missing `!` ?

2021-04-16 12:52 UTC, himdel commented on src/components/execution-environment/repository-form.tsx
> +              isDisabled={this.props.permissions.includes(
missing `!`?

2021-04-16 12:55 UTC, himdel commented on src/containers/execution-environment-detail/base.tsx
> +                          title: "Error: changes weren't save",
*saved

2021-04-16 13:24 UTC, himdel commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    return this.renderDetail();
this change needs to happen for all the tabs, right?

Images and Activity now have..

```
Main
  ExecutionEnvironmentDetailImages
    Main
      Section
```

2021-04-16 13:25 UTC, ZitaNemeckova commented on src/containers/execution-environment-detail/execution_environment_detail.tsx
> +    return this.renderDetail();
just fixing it :)

2021-04-16 13:48 UTC, himdel approved these changes
Seems like all outstanding issues are addressed :+1:

Tested in UI, I'm not seeing any new issues :+1:

2021-04-16 14:02 UTC, newswangerd approved these changes

2021-04-16 14:04 UTC, merged