Remove inbound repo logic
ansible/ansible-hub-ui pull request #3346
Opened 2023-02-21 12:17 UTC by jerabekjiri

Issue: AAH-1778

- Updated collection upload path to `v3/artifacts/collections/`
- removed inbound repo bits

2023-02-22 15:27 UTC, himdel commented
API: https://github.com/ansible/galaxy_ng/pull/1602 (merged now)

Oh, some of the remaining test failures may be because `galaxykit collection upload` will still be doing it the old way..

https://github.com/ansible/galaxykit/blob/main/galaxykit/collections.py#L151
but it probably also needs a version check to work with both pre-4.7 versions and this one.

2023-02-22 19:14 UTC, jerabekjiri commented
@himdel thanks, totally forgot about galaxykit, opened a fix https://github.com/ansible/galaxykit/pull/85 and tested with UI

2023-02-27 07:01 UTC, himdel approved these changes
LGTM, thanks! :) :green_circle:

2023-02-27 16:03 UTC, newswangerd requested changes

2023-02-27 16:03 UTC, newswangerd commented on src/containers/namespace-detail/namespace-detail.tsx
> +    const repositoryUrl = getRepoUrl(namespace.name);
this should be the api endpoint for the service (`/api/galaxy/v3` or `/api/automation-hub/v3`, not `/api/galaxy/content/<namespace>/v3`)

2023-03-01 02:11 UTC, jerabekjiri commented on src/containers/namespace-detail/namespace-detail.tsx
> +    const repositoryUrl = getRepoUrl(namespace.name);
so currently the URL is `http://localhost:8002/api/automation-hub/v3/content/my_namespace/` and looking at URLs

```
pulpcore-manager show_urls | grep /api/automation-hub/content/
/api/automation-hub/content/<str:path>/ galaxy_ng.app.api.views.ApiRootView     galaxy:api:v3:content-root
```
I think this is correct endpoint, there is no endpoint like `/api/automation-hub/v3`?

2023-03-01 02:14 UTC, jerabekjiri commented on src/containers/namespace-detail/namespace-detail.tsx
> +    const repositoryUrl = getRepoUrl(namespace.name);
Also, this is wrong, this should not point to the namespace, but selectedRepo (`inbound-<namespace>` is repo, not namespace, I confused it)

2023-03-02 15:04 UTC, himdel commented
LGTM :+1: 

(ignore the insights test failures, it seems there's a new insights API we're not mocking, causign all tests to fail there)

2023-03-02 16:01 UTC, newswangerd approved these changes

2023-03-02 16:14 UTC, merged