[WIP] Container Registry Manifest
ansible/ansible-hub-ui pull request #336
Opened 2021-03-31 01:31 UTC by himdel

Fixes https://issues.redhat.com/browse/AAH-449
API PR: https://github.com/ansible/galaxy_ng/pull/693 (merged)

Container Registry > detail > tab Images/Activity > click on a sha

---

WIP: depends on #304, also contains #330, #332
rebase, unify Shabel with new 304 ShaLabel, fix colors and make links optional
figure out where labels come from
are individual sizes and layers supposed to be available? (aren't)
some emptystate when loading?

compare to https://hub.docker.com/layers/alpine/library/alpine/latest/images/sha256-4266485e304a825d82c375d3584121b53c802e3540d6b520b212a9f0784d56f5?context=explore

with fake data:

![20210331005113](https://user-images.githubusercontent.com/289743/113077486-c6345980-91c0-11eb-99a6-027e0d099b53.png)

with real data:

![20210331013034](https://user-images.githubusercontent.com/289743/113077490-c92f4a00-91c0-11eb-827d-2af80551c28a.png)

2021-04-09 00:06 UTC, himdel commented
Cc @sbuenafe-rh can you review please? :)

2021-04-09 18:08 UTC, sbuenafe-rh commented
@himdel the only nit picky things are the spacing in the header between the SHA blue label and the tag and the spacing between the header on the cards (Image layers, Environment, Command) and the text body on the cards. 

Does the copy to clipboard button always have that outline?

2021-04-09 18:50 UTC, newswangerd requested changes
This looks great. I just want to get a little bit of feedback from UX before we merge it.

2021-04-09 18:50 UTC, newswangerd commented on src/containers/execution-environment-manifest/execution-environment-manifest.tsx
> +            <ShaLabel digest={digest} />
Showing the full SHA here is okay, since there's plenty of space in the header.

2021-04-09 18:50 UTC, newswangerd commented on src/containers/execution-environment-manifest/execution-environment-manifest.tsx
> +            <ClipboardCopy
This looks really janky. I'd like to get susan's take on how to display the clipboard copy.

2021-04-09 18:50 UTC, newswangerd commented on src/containers/execution-environment-manifest/execution-environment-manifest.tsx
> +                    <>
I'm getting an error in the JS console. I think it's because `key` needs to go in `<>` here.

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ExecutionEnvironmentManifest`. See https://fb.me/react-warning-keys for more information.
    in Fragment (created by ExecutionEnvironmentManifest)
    in ExecutionEnvironmentManifest (created by Route)
```

2021-04-09 18:50 UTC, newswangerd commented on src/containers/execution-environment-manifest/execution-environment-manifest.tsx
> +      digest: this.props.match.params['digest'], // digest or tag until loading done
Setting API response data as top level state makes me a little bit nervous because if the data has to get reloaded you need to remember to update multiple objects in the state. Since this page does have to reload any data, this is fine for now.

2021-04-12 23:32 UTC, himdel commented on src/containers/execution-environment-manifest/execution-environment-manifest.tsx
> +                    <>
fixed, moved the key to the fragment, not the first element inside :+1:

2021-04-12 23:45 UTC, himdel commented
So, @sbuenafe-rh , @newswangerd .. re the sha in the header, we seem to have 3 options:

![114110529-4183c280-98c7-11eb-8d80-b47215d44864](https://user-images.githubusercontent.com/289743/114475448-d8ae8a00-9be7-11eb-80e3-dd72ffd692a6.png)

this is the original version I had

:+1:: same component as other sha labels
:+1:: can have title popup
:grey_question:: 6 lines of custom css
:-1:: short


![20210409190435](https://user-images.githubusercontent.com/289743/114475619-24613380-9be8-11eb-98ca-d3ea03d931cf.png)

this is the patternfly clipboard copy without any modifications

:+1:: the only version supported by patternfly => no custom code
:-1:: no popup
:-1:: looks like an input and a button, which it is


![20210412233324](https://user-images.githubusercontent.com/289743/114475741-583c5900-9be8-11eb-9372-9c1d598384ac.png)

this is copied from https://catalog.redhat.com/software/containers/openshift3/ose-pod/57ea8d029c624c035f96f424?tag=all

:+1:: looks better
:-1:: code (`EcoClipboardCopy`) doesn't seem to be published anywhere => copied 27 lines of css
:-1:: still no popup


(or some combination thereof)

What do you think? Stick with option 2 until we can get a better component for patternfly? Or just put a long label there and expect people to be able to select and copy manually?

---

@sbuenafe-rh the last two screenshots have the spacing fixed, is it better now? :)

2021-04-13 13:03 UTC, sbuenafe-rh commented
@himdel @newswangerd The 3rd option looks the best! thanks for fixing the spacing :)

2021-04-13 13:07 UTC, newswangerd approved these changes

2021-04-13 23:50 UTC, merged