Update approval dashboard page to use new collection version search endpoint
ansible/ansible-hub-ui pull request #3406
Opened 2023-03-07 13:47 UTC by jerabekjiri

Issue: [AAH-767](https://issues.redhat.com/browse/AAH-767)

Lots of changes, so I'm splitting this issue into more parts. 
This PR updates `Approval dashboard` page and `my-imports` page.

2023-03-08 22:28 UTC, himdel commented on src/api/repository-distributions.ts
> +        });
```suggestion
          return mappedRepoHrefToDistro;
```

and you don't need the `return new Promise` bit :)

2023-03-08 22:30 UTC, himdel commented on src/api/repository-distributions.ts
> +        params['page_size'] = 999;
This would break once a repo has a 1000 distributions, right? I guess it's unlikely, but any way to avoid that?

2023-03-15 11:58 UTC, jerabekjiri commented on src/api/repository-distributions.ts
> +        params['page_size'] = 999;
yep, reworked it multiple times plus this was really inefficient. Now I only get distribution when it's needed and I don't need to do any merging of distribution to collection version

2023-03-24 14:15 UTC, newswangerd requested changes
I'm just going to review the user experience and not the code, so the exact lines where I put my comments don't necessarily correlate to where the code needs to change.

2023-03-24 14:15 UTC, newswangerd commented on src/components/cards/collection-card.tsx
> +              <Trans>
1. If the namespace is empty, use the namespace name from the collection
2. I don't think this is the right place for the repository name. It implies certified is part of the namespace. Maybe move it to (3) and replace the certification badge with the name of the repository (this will require some changes for insights mode where the certified repository is called published) or add a new line under "provided by" that's "Repository: rh-certified"

<img width="304" alt="Screenshot 2023-03-24 at 9 53 56 AM" src="https://user-images.githubusercontent.com/6063371/227541081-93042f9a-909f-46a1-ba51-93b997cd0092.png">

2023-03-24 14:15 UTC, newswangerd commented on src/containers/namespace-list/namespace-list.tsx
>            onCreateSuccess={(result) =>
The collection list on the namespaces page needs to display the repository that the collection is in

<img width="911" alt="Screenshot 2023-03-24 at 10 01 04 AM" src="https://user-images.githubusercontent.com/6063371/227542416-90312509-ac66-4a50-adb7-3beefb205d4c.png">

2023-03-24 14:15 UTC, newswangerd commented on src/components/collection-list/collection-filter.tsx
>  } from '@patternfly/react-core';
Repository filter is not populated

<img width="471" alt="Screenshot 2023-03-24 at 10 04 35 AM" src="https://user-images.githubusercontent.com/6063371/227542829-9d9ce6a5-3189-47e3-9a08-48cd75a4ea8a.png">

2023-03-24 14:15 UTC, newswangerd commented on src/components/collection-list/collection-filter.tsx
>  } from '@patternfly/react-core';
Namespace collection view should have the same filters as the collection search page

<img width="427" alt="Screenshot 2023-03-24 at 10 05 26 AM" src="https://user-images.githubusercontent.com/6063371/227543014-37e03293-0b72-4453-940d-814a66aa7896.png">

2023-03-24 14:15 UTC, newswangerd commented on src/containers/collection-detail/collection-content.tsx
>      const params = ParamHelper.parseParamString(props.location.search);
1. Since this is displaying the repo and not a distribution, this should have a "distributions" tab that displays the distributions associated with the repository with information for configuring the client to connect to that distribution (like the copy cli config works on the current repository management tab)
2. Add a note here saying "to download this collection, configure your client to connect to one of this repositories distributions" with a link to the distributions tab from 1.

<img width="1135" alt="Screenshot 2023-03-24 at 10 07 39 AM" src="https://user-images.githubusercontent.com/6063371/227543842-7825caf0-c3c5-4648-8f50-5a61b72f71ef.png">

2023-03-24 15:25 UTC, jerabekjiri commented on src/containers/namespace-list/namespace-list.tsx
>            onCreateSuccess={(result) =>
@newswangerd namespaces are global and I don't know how to get repository by namespace? I was only able to get that information from cross repo search API, but if namespace is empty I can't get repository name.

2023-03-24 15:30 UTC, jerabekjiri commented on src/components/collection-list/collection-filter.tsx
>  } from '@patternfly/react-core';
@newswangerd Do we really need to be filtering by repository and namespace in namespace detail?

2023-03-27 10:03 UTC, jerabekjiri commented
UI changes:
- Collection list item: repository badge
![Screenshot from 2023-03-27 11-58-03](https://user-images.githubusercontent.com/19647757/227910080-72afa8fc-c435-4728-9e11-c129661b8d5b.png)

- Collection card: repository badge
![Screenshot from 2023-03-27 11-37-14](https://user-images.githubusercontent.com/19647757/227910124-93f4b918-4211-475d-90b4-5239a8ede1cf.png)

- Distribution tab
![Screenshot from 2023-03-27 11-09-02](https://user-images.githubusercontent.com/19647757/227910256-d010efbf-ca90-4230-9564-62b2121526de.png)

2023-03-28 17:16 UTC, jerabekjiri commented
Closed in favor of https://github.com/ansible/ansible-hub-ui/pull/3467

2023-03-28 17:16 UTC, closed without merging