[Cross Repo Search] Namespace detail, collection list and collection detail refactor
ansible/ansible-hub-ui pull request #3467
Opened 2023-03-28 01:24 UTC by jerabekjiri

Issue: AAH-767

2023-03-28 18:17 UTC, newswangerd requested changes
Mostly looking pretty good. Found a few UX things and some bugs

2023-03-28 18:17 UTC, newswangerd commented on src/containers/namespace-detail/namespace-detail.tsx
> -                  repo={this.context.selectedRepo}
Show the namespace logo on the collection list view (like the list layout on the search page does now)

2023-03-28 18:17 UTC, newswangerd commented on src/components/collection-detail/collection-info.tsx
> +                      <ExternalLinkAltIcon />
put the link on the "distributions" word. The `ExternalLinkAltIcon` should only be used for links to external web pages.

2023-03-28 20:20 UTC, jerabekjiri commented on src/containers/search/search.tsx
> +        'repository__name',
nice catch

2023-03-28 21:00 UTC, jerabekjiri commented on src/containers/search/search.tsx
> +      !filterIsSet(params, [
fixed, now it only sends requests if repository filter is selected

2023-03-29 15:09 UTC, newswangerd approved these changes
Overall looks good. Only thing I noticed is unpriviledged users can see the control dropdown on the list view. We don't have a good solution for this right now, so I would say just check the user's global permissions to show this.

Same problem on the collection page. For this one you can query the namespaces API to get the user's permissions on the given namespace.

![image](https://user-images.githubusercontent.com/6063371/228583509-03831ef4-219d-4adf-bb09-fc94ac941333.png)

2023-03-29 21:11 UTC, himdel commented
Screenshot test failure expected - removes the repo filter from collections :+1: 
(Insights are also unrelated)
restarting collection_upload...

2023-03-29 21:14 UTC, jerabekjiri commented
@himdel I'm trying to figure out what is the issue with collection_upload, It's passing locally

2023-03-29 22:11 UTC, merged