Repair approval process and modal
ansible/ansible-hub-ui pull request #3468
Opened 2023-03-28 13:15 UTC by MilanPospisil

No-Issue

2023-03-28 14:58 UTC, newswangerd requested changes

2023-03-28 14:58 UTC, newswangerd commented on src/components/approve-modal/approve-modal.tsx
> +                promiseCopyOrMove = Repositories.moveCollectionVersion(
When auto signing is enabled, you need to include the signing service HREF in the post request.

You can get the name of the signing service from `_ui/v1/settings/` and look up the href on `pulp/api/v3/signing-services/?name=<NAME>`

2023-03-29 09:50 UTC, MilanPospisil commented on src/components/approve-modal/approve-modal.tsx
> +                promiseCopyOrMove = Repositories.moveCollectionVersion(
Thank you for catching that.

2023-03-29 11:09 UTC, MilanPospisil commented on src/components/approve-modal/approve-modal.tsx
> +                promiseCopyOrMove = Repositories.moveCollectionVersion(
Done. But I dont know if this is correct. I have also rewrited approval method to async (handling so many API calls including conditions with then was crazy), so its easier to read.

2023-03-29 16:36 UTC, newswangerd approved these changes

2023-03-29 23:45 UTC, himdel commented on src/containers/certification-dashboard/certification-dashboard.tsx
> +      .then((versionWithRepos: any) => {
```suggestion
      .then((versionWithRepos) => {
```

2023-03-30 00:24 UTC, himdel commented
Merging, so I can use the modal in #3431 :)

2023-03-30 00:24 UTC, merged