minor edit to approval status message
ansible/ansible-hub-ui pull request #514
Opened 2021-06-03 19:01 UTC by ShaiahWren

Hi Henderson! :)

Issue: https://issues.redhat.com/browse/AAH-169

A minor change to import-console.tsx. Approval status now reads "could not be determined yet".

2021-06-03 19:55 UTC, hendersonreed requested changes
@ShaiahWren this is great - looks like @awcrosby  suggested wording along the lines of 'approval status could not be determined yet', so I see why you went with that.

Is there a good reason for using that wording instead of something that's a little more accurate, like "awaiting review" or something like that? 'not determined' implies that galaxy_ng the product isn't sure about the approval status, when really galaxy_ng _does_ know the status of the collection - it's in limbo and needs to be approved or rejected.

2021-06-03 20:02 UTC, awcrosby commented
This message will only show until the `CollectionVersion` is moved from the `inbound-<ns>` repo to either `staging` or `published` - so it is a temporary statement until the task to move the `CollectionVersion` completes.

"awaiting review" would be wrong here since it may not require review, it may go directly to `published`. We suggested just adding "yet" after talking with david and calvin today.

2021-06-03 20:02 UTC, awcrosby approved these changes

2021-06-04 10:44 UTC, ZitaNemeckova commented
@hendersonreed are you ok with Andrew's explanation?

2021-06-04 15:58 UTC, hendersonreed approved these changes
Just went in and double-checked this, was unable to reproduce the original bug - it now says "waiting for approval" when a collection has been neither approved nor rejected. 

Either it was my error when I reported the bug, or it has been fixed during some other PR. I'd say 'could not be determined yet' is ideal. Thanks!

2021-06-04 18:49 UTC, ShaiahWren commented
pr closed.

2021-06-04 18:49 UTC, merged