[WIP] Test group permissions - if it can (or cant) see groups, add groups, delete or change groups.
ansible/ansible-hub-ui pull request #681
Opened 2021-07-22 12:50 UTC by MilanPospisil

Thank you for a new Pull Request!

Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ansible/ansible-hub-ui/blob/master/developer_guidelines.md

Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.

Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description as necessary to get the reviewer up to the same domain knowledge level as yourself
* Keep code changes as short as possible and implementing a single feature/fix/refactoring, when possible

Links [Optional]
----------------

* http://documentation.for/library/that/I/am/adding
* [PR relevant issue or pull_request](#123)

Steps for Testing/QA [Optional]
-------------------------------

If there are any manual steps that you would like the reviewer(s) to take to verify your changes, please describe in detail the steps to reproduce the features added by the pull request, or the bug before and after the change.

2021-07-28 14:44 UTC, himdel commented on test/cypress/fixtures/example.json
> +{
remove please, and add `test/cypress/fixtures/example.json` to our repo's `.gitignore` so we don't add it again

(this gets created whenever cypress thinks it's being installed for the first time)

2021-07-28 14:46 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = urljoin(baseUrl, 'ui/group-list');
groups are in menu, so we should probably use ` cy.menuGo('User Access > Groups')` if possible

2021-07-28 14:52 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +    // base group is needed because if no group is in list, you can always add Group even if you dont have permissions
sounds like baseGroup is not needed at all, and we need to fix the button to check permissions?

Which button are you talking about?

2021-07-28 14:52 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  it('beforeAll', () => {});
empty, delete?

2021-07-28 14:53 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  it('it cant see groups', () => {
typo `cant` -> `can\'t`

2021-07-28 14:57 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  it('can view groups', () => {
these are not unit tests, we should merge user3 into 1 test...

    let user = 'user3';
    cy.login(user, user + 'Password');
    cy.menuGo('User Access > Groups');
    
    // can view groups
    cy.contains('Groups');
    
    // can not change groups
    cy.contains('button', 'Edit').should('not.exist');
    
    // can not add groups
    cy.contains('button', 'View').should('not.exist');
    
    // can not delete groups
    cy.contains('button', 'Delete').should('not.exist');

2021-07-28 14:58 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  it('can view groups', () => {
also, "can not add groups" vs 'View' .. wrong description?

2021-08-02 12:35 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = urljoin(baseUrl, 'ui/group-list');
But I want to check if the user really can not view the groups using URL. Do you really need menu go instead, or should I test both?

2021-08-02 12:40 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('beforeAll', () => {});
Ok.

2021-08-02 12:46 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('it cant see groups', () => {
Ok.

2021-08-02 12:54 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('can view groups', () => {
I corrected the descriptions. Do you really want it merged? I though if something fail, you will exactly see what permission is wrong. If you merge this, you will se that some permission of user3 failed, but you will not know quickly which one.

2021-08-02 12:58 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
As admin?

2021-08-02 13:44 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +    // base group is needed because if no group is in list, you can always add Group even if you dont have permissions
Maybe it is already fixed, because I can not reproduce the error :-( So I deleted baseGroup.

2021-08-02 13:44 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('beforeAll', () => {});
Ok.

2021-08-02 13:45 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('it cant see groups', () => {
Ok

2021-08-02 13:47 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
yes :) Can you share the failing request url, and the response code and data please? :)

2021-08-02 15:13 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  it('can view groups', () => {
Yes please, all of these are on the same page, not dependent on each other, merging them will save us 3 page loads and 3 logins.

2021-08-02 15:15 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = urljoin(baseUrl, 'ui/group-list');
Aah, that's fine then :) Use the menu for the positive cases, if possible, but for testng a user who doesn't have rights to see groups in the menu, it makes sense to use the url :+1: 

`cy.visit('/ui/group-list')` should still work :)

2021-08-03 06:08 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = urljoin(baseUrl, 'ui/group-list');
Ah, and I see that when you do not have rights to see groups, there is also no menu path.

2021-08-03 06:12 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  it('can view groups', () => {
Ok, done. Page loads, but not logins when my cookieLogin is used :-)

2021-08-03 06:14 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
We looked at it with Zita and she told me that you now know about this issue. As admin, there is no problem because you have rights to see users. I did not tested it with user rights, so when you want to delete group, the dialog also tries to show what users will be affected and the user has no rights to see the users, it will return error and test automatically fails.

2021-08-03 06:20 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
I will add rights to see the users.

2021-08-03 08:04 UTC, MilanPospisil commented on test/cypress/fixtures/example.json
> +{
ok

2021-08-03 12:48 UTC, himdel commented on .gitignore
> +test/fixtures/*
just `test/fixtures/example.json` please. The directory can actually contain useful fixtures.

2021-08-03 12:50 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = '/ui/group-list';
unused now

2021-08-03 13:18 UTC, himdel commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
:+1: the solution makes sense

---

But when such a problem is found, it's necessary to write it down in a way others can test and debug this. So adding the requested info myself then, in the future this will be your job for issues you find :)

1. Create group with just the "View group" & "Delete group" permissions, no "View user"
1. Create a user in that group, not superuser.
1. Create an extra group to be deleted.
1. Log in as the new user
1. Go to Groups
1. Click Delete (on the extra group)

A dialog pops up with infinite "Checking for affected users... " spinner,
a request to `/api/automation-hub/_ui/v1/users/?groups__name=def&offset=0&limit=10`
fails with 403, `{errors:[{status: "403", code: "permission_denied", title: "You do not have permission to perform this action."}]}`

(The modal still deletes the group after the user stops waiting and confirms the modal.)

2021-08-03 20:06 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +    // The group should be deleted, because user has rights for it, API should not return error
Sorry, I did not know that you still want this after I solved the problem.

2021-08-04 08:39 UTC, MilanPospisil commented on test/cypress/integration/group_permissions.js
> +  let groupsUrl = '/ui/group-list';
ok.

2021-08-04 18:08 UTC, himdel requested changes
Maybe not quite there yet... cypress now fails on group_permissions and group_management, sounds related :)

```
    <testcase name="Group Permissions Tests it can&apos;t view groups" time="0.0000" classname="it can&apos;t view groups">
      <failure message="Timed out retrying after 4000ms: Expected not to find content: &apos;Groups&apos; but continuously found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected not to find content: 'Groups' but continuously found it.
    at Context.eval (http://localhost:8002/__cypress/tests?p=cypress/integration/group_permissions.js:147:27)]]></failure>
    </testcase>

    <testcase name="Hub Group Management Tests &quot;before each&quot; hook for &quot;admin user can add/remove permissions to/from a group&quot;" time="0.0000" classname="&quot;before each&quot; hook for &quot;admin user can add/remove permissions to/from a group&quot;">
      <failure message="The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Request failed with status code 403
...
```

2021-08-05 16:23 UTC, himdel approved these changes

2021-08-05 16:23 UTC, merged