[WIP]Add Task detail page
ansible/ansible-hub-ui pull request #733
Opened 2021-08-02 10:59 UTC by ZitaNemeckova

TODO:

- [ ] find task with progress report
- [ ] parent task is same as selected task
- [ ] child task doesn't exist
- [ ] Reserve resource - what, how?
- [ ] human readable names

2021-08-11 01:29 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +      parentTaskId = splitedHref[splitedHref.length - 2];
looks like we already have a helper for this... 

`import { parsePulpIDFromURL } from 'src/utilities/parse-pulp-id';`

(from https://github.com/ansible/ansible-hub-ui/pull/786#discussion_r686056162)

2021-08-18 01:43 UTC, himdel commented on src/containers/task-management/task-list-view.tsx
> +    let taskId = splitedHref[splitedHref.length - 2];
`parsePulpIDFromURL`

2021-08-18 04:14 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +                                        {capitalize(key)}
do we know enough about the keys to be able to translate them instead of just capitalizing?

2021-08-18 04:19 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +            parenTask = result.data;
parenTask != parentTask

2021-08-18 04:20 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +          childTasks: childTasks,
(these could be using the es6 syntax of just `childTasks, parentTask`)

2021-08-18 11:22 UTC, ZitaNemeckova commented on src/containers/task-management/task_detail.tsx
> +                                        {capitalize(key)}
I'll ask about it and let you know asap.

2021-08-18 14:25 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +  private loadContent() {
would it make sense to precompute the pretty name here when loading the task, instead of the 10 places throughout the file?

2021-08-19 08:42 UTC, ZitaNemeckova commented on src/containers/task-management/task_detail.tsx
> +  private loadContent() {
Fixed, Leaving it only for child and parent tasks.

2021-08-30 14:36 UTC, himdel commented
UX issue .. the same button is called "Stop" on one screen and "Cancel Task" on the detail screen.
We should not have different button labels for the same action :)

2021-08-30 15:12 UTC, sbuenafe-rh commented
@ZitaNemeckova @himdel I would change the **Cancel task** on the detail screen to **Stop task**

2021-09-01 17:40 UTC, newswangerd requested changes

2021-09-01 17:40 UTC, newswangerd commented on src/containers/task-management/task_detail.tsx
> +        this.props.history.push(Paths.notFound);
I'm getting redirected to the 404 page when navigating to tasks with

```
    "reserved_resources_record": [
        "/api/v3/distributions/"
    ]
```

2021-09-02 00:19 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +                                          {capitalize(key)}
Sounds like maybe we know the keys now?
What about something like..

```suggestion
                                          {{ message: t`Message`, code: t`Code`, state: t`State`, done: t`Done` }[key] || capitalize(key)}
```

(+- linter :))

2021-09-02 00:20 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +                      {_`Progress messages`}
Oh, and you'll have to change all of these `_` to `t`, sorry :)

( https://github.com/ansible/ansible-hub-ui/pull/810 )

2021-09-02 00:26 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +                return true;
should these catches Alert? (parent task, child tasks, reserved_resources_record)

(I'm not opposed to unifying these in a separate PR :).)

2021-09-02 08:11 UTC, ZitaNemeckova commented on src/containers/task-management/task_detail.tsx
> +                return true;
I vote separate PR :D

2021-09-02 14:40 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +                      {_`Progress messages`}
https://github.com/ansible/ansible-hub-ui/pull/810 is merged

2021-09-03 15:14 UTC, himdel commented on src/containers/task-management/task_detail.tsx
> +      return <Redirect to={redirect}></Redirect>;
```suggestion
      return <Redirect push to={redirect}></Redirect>;
```

2021-09-03 15:28 UTC, himdel approved these changes
Not seeing any new issues,
pulp resource 404s no longer affect the rest of the screen,
LGTM :+1: :)

2021-09-07 18:57 UTC, newswangerd requested changes

2021-09-07 18:57 UTC, newswangerd commented on src/containers/task-management/task_detail.tsx
> +        this.setState({ redirect: Paths.notFound });
I'm still getting redirected to the 404 page. The root cause is that there is an error here that `catch` is picking up and interpreting as a 404.

If I do
```
      .catch((e) => {
        console.log(e)
        // this.setState({ redirect: Paths.notFound });
      });
```
I get the following error

```
TypeError: resource.split(...).at is not a function
    loadContent task_detail.tsx:425
    loadContent task_detail.tsx:420
    promise callback*loadContent task_detail.tsx:388
    componentDidMount task_detail.tsx:72
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
    App standalone-loader.tsx:382
    componentDidMount routes.tsx:92
    promise callback*componentDidMount/< routes.tsx:91
    promise callback*componentDidMount routes.tsx:89
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
    emit core.development.js:308
    emit core.development.js:307
    activate core.development.js:419
    _callee$ l10n.ts:23
    Babel 10
    activate App.aefba559fac893859cf2.js:24037
    ts l10n.ts:26
    Webpack 7
    ```

Here's the full task I'm loading:

```

{
    "pulp_href": "/pulp/api/v3/tasks/faf70a47-e93c-43a0-ae63-c1ca367cc2f9/",
    "pulp_created": "2021-09-03T13:02:48.805050Z",
    "state": "completed",
    "name": "pulpcore.app.tasks.base.general_create",
    "logging_cid": "",
    "started_at": "2021-09-03T13:02:48.863318Z",
    "finished_at": "2021-09-03T13:02:48.986545Z",
    "error": null,
    "worker": null,
    "parent_task": null,
    "child_tasks": [],
    "task_group": null,
    "progress_reports": [],
    "created_resources": [
        null
    ],
    "reserved_resources_record": [
        "/api/v3/distributions/"
    ]
}
```

It seems like this error only happens in Firefox, not Chrome

2021-09-10 12:19 UTC, ZitaNemeckova commented on src/containers/task-management/task_detail.tsx
> +        this.setState({ redirect: Paths.notFound });
@newswangerd Replace the unknown function `Array.at(number)` so it should work in Firefox as well.

2021-09-10 15:10 UTC, newswangerd approved these changes
Thanks!

2021-09-10 15:44 UTC, merged