Namespace and collection deletion UI
ansible/ansible-hub-ui pull request #871
Opened 2021-09-02 22:55 UTC by jerabekjiri

Issue: [AAH-709](https://issues.redhat.com/browse/AAH-709) and [AAH-715](https://issues.redhat.com/browse/AAH-715)

Created UI part for namespace and collection deletion. Added`DeleteCollectionModal` for deleting collections and namespaces.

#### Delete namespace modal
![Screenshot from 2021-09-03 00-36-08](https://user-images.githubusercontent.com/19647757/131925837-7778200b-07ef-459f-b229-64d5b9a9119b.png)

#### Delete entire collection
![Screenshot from 2021-09-03 00-31-59](https://user-images.githubusercontent.com/19647757/131925829-63460b3f-970f-47dc-93cb-9e9eb42c23a0.png)

#### Delete collection version
![Screenshot from 2021-09-03 00-37-53](https://user-images.githubusercontent.com/19647757/131925841-a7a4ed81-f9ac-4e1e-bce4-252cae2f7bd9.png)

2021-09-09 10:57 UTC, ZitaNemeckova commented
I have a `arista` namespace with a published collection. When a go to arita detail page and change a repository from `pusblished` to `community` I can try to delete it but it fails with `{"errors":[{"status":"400","code":"invalid","title":"Invalid input.","detail":"Namespace arista cannot be deleted because there are still collections associated with it."}]}`

2021-09-09 12:14 UTC, ZitaNemeckova commented on src/containers/collection-detail/delete-collection-modal.tsx
> +  private deleteNamespace({ name }) {
It would be better to move this function to the container and pass it as a prop.

2021-09-09 12:20 UTC, ZitaNemeckova commented on src/containers/collection-detail/delete-collection-modal.tsx
> +          namespace
It would be better to pass title and description in params so the component as dumb as possible.

2021-09-09 12:26 UTC, ZitaNemeckova requested changes
It's on a good way :) There's a fwe things that need rework.
- There' s "collection deletion" logic that should come in it's own PR. 
- Any component should be as dumb as possible. The logic should stay in a container if possible. 
- Why not use `DeleteModal` component instead of create a new component?

2021-09-10 01:54 UTC, jerabekjiri commented
- Created a new component `DeleteModalWithConfirm` which uses `DeleleModal`, but already includes confirmation UI part and logic for that, this could be nice for reusing later, since all content deletion modals are same and could be reused like that :)
- Fixed mentioned error by getting all namespace's repositories and checking if it has collections.
- Removed collection deletion leftovers
> Any component should be as dumb as possible. The logic should stay in a container if possible.

Good suggestion, thanks, It really made no sense mixing collection and namespace into one delete modal, also when there's container deletion and might others in future :grin: :+1:

2021-09-13 13:08 UTC, jerabekjiri commented
I will investigate that test fail more, my Chrome crashes on this local test, but in Firefox it passes normally.

2021-09-14 18:15 UTC, himdel commented on src/api/namespace.ts
> +  deleteNamespace(name) {
`NamespaceAPI.delete(name)` already exists from the base class

2021-09-23 15:25 UTC, ZitaNemeckova approved these changes
LGTM 👍 There's a style that should be moved to sccs file in followup PR.

2021-09-23 15:25 UTC, merged